import { PrismaClient } from '../../src/generated/prisma';

export async function seedAirports(prisma: PrismaClient) {
  console.log('🛫 Seeding airports...');

  const airports = [
    // Brasil - Principais Aeroportos
    {
      iataCode: 'GRU',
      icaoCode: 'SBGR',
      name: 'Aeroporto Internacional de São Paulo/Guarulhos',
      city: 'São Paulo',
      state: 'São Paulo',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Southeast',
      continent: 'South America',
      latitude: -23.432075,
      longitude: -46.469511,
      timezone: 'America/Sao_Paulo',
      isInternational: true,
      popularityScore: 100,
      alternativeAirports: ['CGH', 'VCP'],
    },
    {
      iataCode: 'CGH',
      icaoCode: 'SBSP',
      name: 'Aeroporto de Congonhas',
      city: 'São Paulo',
      state: 'São Paulo',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Southeast',
      continent: 'South America',
      latitude: -23.626692,
      longitude: -46.655981,
      timezone: 'America/Sao_Paulo',
      isInternational: false,
      popularityScore: 95,
      alternativeAirports: ['GRU', 'VCP'],
    },
    {
      iataCode: 'GIG',
      icaoCode: 'SBGL',
      name: 'Aeroporto Internacional do Rio de Janeiro/Galeão',
      city: 'Rio de Janeiro',
      state: 'Rio de Janeiro',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Southeast',
      continent: 'South America',
      latitude: -22.809999,
      longitude: -43.250555,
      timezone: 'America/Sao_Paulo',
      isInternational: true,
      popularityScore: 90,
      alternativeAirports: ['SDU'],
    },
    {
      iataCode: 'SDU',
      icaoCode: 'SBRJ',
      name: 'Aeroporto Santos Dumont',
      city: 'Rio de Janeiro',
      state: 'Rio de Janeiro',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Southeast',
      continent: 'South America',
      latitude: -22.910461,
      longitude: -43.163133,
      timezone: 'America/Sao_Paulo',
      isInternational: false,
      popularityScore: 85,
      alternativeAirports: ['GIG'],
    },
    {
      iataCode: 'BSB',
      icaoCode: 'SBBR',
      name: 'Aeroporto Internacional de Brasília',
      city: 'Brasília',
      state: 'Distrito Federal',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Central-West',
      continent: 'South America',
      latitude: -15.869167,
      longitude: -47.920833,
      timezone: 'America/Sao_Paulo',
      isInternational: true,
      popularityScore: 88,
      alternativeAirports: [],
    },
    {
      iataCode: 'SSA',
      icaoCode: 'SBSV',
      name: 'Aeroporto Internacional de Salvador',
      city: 'Salvador',
      state: 'Bahia',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Northeast',
      continent: 'South America',
      latitude: -12.910994,
      longitude: -38.331044,
      timezone: 'America/Bahia',
      isInternational: true,
      popularityScore: 82,
      alternativeAirports: [],
    },
    {
      iataCode: 'REC',
      icaoCode: 'SBRF',
      name: 'Aeroporto Internacional do Recife/Guararapes',
      city: 'Recife',
      state: 'Pernambuco',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Northeast',
      continent: 'South America',
      latitude: -8.126794,
      longitude: -34.923039,
      timezone: 'America/Recife',
      isInternational: true,
      popularityScore: 80,
      alternativeAirports: [],
    },
    {
      iataCode: 'FOR',
      icaoCode: 'SBFZ',
      name: 'Aeroporto Internacional de Fortaleza',
      city: 'Fortaleza',
      state: 'Ceará',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Northeast',
      continent: 'South America',
      latitude: -3.776283,
      longitude: -38.532556,
      timezone: 'America/Fortaleza',
      isInternational: true,
      popularityScore: 78,
      alternativeAirports: [],
    },
    {
      iataCode: 'FLN',
      icaoCode: 'SBFL',
      name: 'Aeroporto Internacional de Florianópolis',
      city: 'Florianópolis',
      state: 'Santa Catarina',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'South',
      continent: 'South America',
      latitude: -27.670489,
      longitude: -48.552511,
      timezone: 'America/Sao_Paulo',
      isInternational: true,
      popularityScore: 75,
      alternativeAirports: [],
    },
    {
      iataCode: 'POA',
      icaoCode: 'SBPA',
      name: 'Aeroporto Internacional Salgado Filho',
      city: 'Porto Alegre',
      state: 'Rio Grande do Sul',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'South',
      continent: 'South America',
      latitude: -29.994428,
      longitude: -51.171428,
      timezone: 'America/Sao_Paulo',
      isInternational: true,
      popularityScore: 76,
      alternativeAirports: [],
    },
    {
      iataCode: 'CNF',
      icaoCode: 'SBCF',
      name: 'Aeroporto Internacional de Belo Horizonte/Confins',
      city: 'Belo Horizonte',
      state: 'Minas Gerais',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Southeast',
      continent: 'South America',
      latitude: -19.624444,
      longitude: -43.971944,
      timezone: 'America/Sao_Paulo',
      isInternational: true,
      popularityScore: 74,
      alternativeAirports: ['PLU'],
    },
    {
      iataCode: 'CWB',
      icaoCode: 'SBCT',
      name: 'Aeroporto Internacional Afonso Pena',
      city: 'Curitiba',
      state: 'Paraná',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'South',
      continent: 'South America',
      latitude: -25.528475,
      longitude: -49.175775,
      timezone: 'America/Sao_Paulo',
      isInternational: true,
      popularityScore: 72,
      alternativeAirports: [],
    },
    {
      iataCode: 'MAO',
      icaoCode: 'SBEG',
      name: 'Aeroporto Internacional de Manaus/Eduardo Gomes',
      city: 'Manaus',
      state: 'Amazonas',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'North',
      continent: 'South America',
      latitude: -3.038611,
      longitude: -60.049722,
      timezone: 'America/Manaus',
      isInternational: true,
      popularityScore: 82,
      alternativeAirports: [],
    },
    {
      iataCode: 'SLZ',
      icaoCode: 'SBSL',
      name: 'Aeroporto Internacional Marechal Cunha Machado',
      city: 'São Luís',
      state: 'Maranhão',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Northeast',
      continent: 'South America',
      latitude: -2.585360,
      longitude: -44.234139,
      timezone: 'America/Fortaleza',
      isInternational: true,
      popularityScore: 70,
      alternativeAirports: [],
    },
    {
      iataCode: 'JJD',
      icaoCode: 'SBJE',
      name: 'Aeroporto Regional de Jericoacoara Comandante Ariston Pessoa',
      city: 'Jijoca de Jericoacoara',
      state: 'Ceará',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Northeast',
      continent: 'South America',
      latitude: -2.906444,
      longitude: -40.350833,
      timezone: 'America/Fortaleza',
      isInternational: true,
      popularityScore: 60,
      alternativeAirports: ['FOR'],
    },
    {
      iataCode: 'FEN',
      icaoCode: 'SBFN',
      name: 'Aeroporto de Fernando de Noronha',
      city: 'Fernando de Noronha',
      state: 'Pernambuco',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Northeast',
      continent: 'South America',
      latitude: -3.854928,
      longitude: -32.423202,
      timezone: 'America/Noronha',
      isInternational: true,
      popularityScore: 65,
      alternativeAirports: ['REC'],
    },
    {
      iataCode: 'BYO',
      icaoCode: 'SBDB',
      name: 'Aeroporto Regional de Bonito',
      city: 'Bonito',
      state: 'Mato Grosso do Sul',
      country: 'Brasil',
      countryCode: 'BR',
      region: 'Central-West',
      continent: 'South America',
      latitude: -21.247311,
      longitude: -56.452499,
      timezone: 'America/Campo_Grande',
      isInternational: false,
      popularityScore: 55,
      alternativeAirports: [],
    },

    // América do Sul
    {
      iataCode: 'EZE',
      icaoCode: 'SAEZ',
      name: 'Aeropuerto Internacional Ministro Pistarini',
      city: 'Buenos Aires',
      country: 'Argentina',
      countryCode: 'AR',
      region: 'South America',
      continent: 'South America',
      latitude: -34.822222,
      longitude: -58.535833,
      timezone: 'America/Argentina/Buenos_Aires',
      isInternational: true,
      popularityScore: 92,
      alternativeAirports: ['AEP'],
    },

    // Estados Unidos - Principais Aeroportos
    {
      iataCode: 'SFO',
      icaoCode: 'KSFO',
      name: 'San Francisco International Airport',
      city: 'San Francisco',
      state: 'California',
      country: 'United States',
      countryCode: 'US',
      region: 'North America',
      continent: 'North America',
      latitude: 37.6213,
      longitude: -122.3790,
      timezone: 'America/Los_Angeles',
      isInternational: true,
      popularityScore: 98,
      alternativeAirports: ['OAK', 'SJC'],
    },
    {
      iataCode: 'AEP',
      icaoCode: 'SABE',
      name: 'Aeroparque Jorge Newbery',
      city: 'Buenos Aires',
      country: 'Argentina',
      countryCode: 'AR',
      region: 'South America',
      continent: 'South America',
      latitude: -34.559167,
      longitude: -58.415833,
      timezone: 'America/Argentina/Buenos_Aires',
      isInternational: false,
      popularityScore: 85,
      alternativeAirports: ['EZE'],
    },
    {
      iataCode: 'SCL',
      icaoCode: 'SCEL',
      name: 'Aeropuerto Internacional Arturo Merino Benítez',
      city: 'Santiago',
      country: 'Chile',
      countryCode: 'CL',
      region: 'South America',
      continent: 'South America',
      latitude: -33.393,
      longitude: -70.785833,
      timezone: 'America/Santiago',
      isInternational: true,
      popularityScore: 93,
      alternativeAirports: [],
    },
    {
      iataCode: 'LIM',
      icaoCode: 'SPJC',
      name: 'Aeropuerto Internacional Jorge Chávez',
      city: 'Lima',
      country: 'Peru',
      countryCode: 'PE',
      region: 'South America',
      continent: 'South America',
      latitude: -12.021889,
      longitude: -77.114319,
      timezone: 'America/Lima',
      isInternational: true,
      popularityScore: 84,
      alternativeAirports: [],
    },
    {
      iataCode: 'MVD',
      icaoCode: 'SUMU',
      name: 'Aeropuerto Internacional de Carrasco',
      city: 'Montevideo',
      country: 'Uruguay',
      countryCode: 'UY',
      region: 'South America',
      continent: 'South America',
      latitude: -34.838417,
      longitude: -56.030806,
      timezone: 'America/Montevideo',
      isInternational: true,
      popularityScore: 70,
      alternativeAirports: [],
    },
    {
      iataCode: 'BOG',
      icaoCode: 'SKBO',
      name: 'Aeropuerto Internacional El Dorado',
      city: 'Bogotá',
      country: 'Colombia',
      countryCode: 'CO',
      region: 'South America',
      continent: 'South America',
      latitude: 4.701594,
      longitude: -74.146947,
      timezone: 'America/Bogota',
      isInternational: true,
      popularityScore: 81,
      alternativeAirports: [],
    },

    // América do Norte
    {
      iataCode: 'MIA',
      icaoCode: 'KMIA',
      name: 'Miami International Airport',
      city: 'Miami',
      state: 'Florida',
      country: 'United States',
      countryCode: 'US',
      region: 'North America',
      continent: 'North America',
      latitude: 25.79325,
      longitude: -80.290556,
      timezone: 'America/New_York',
      isInternational: true,
      popularityScore: 94,
      alternativeAirports: ['FLL'],
    },
    {
      iataCode: 'MCO',
      icaoCode: 'KMCO',
      name: 'Orlando International Airport',
      city: 'Orlando',
      state: 'Florida',
      country: 'United States',
      countryCode: 'US',
      region: 'North America',
      continent: 'North America',
      latitude: 28.429444,
      longitude: -81.308889,
      timezone: 'America/New_York',
      isInternational: true,
      popularityScore: 91,
      alternativeAirports: [],
    },
    {
      iataCode: 'JFK',
      icaoCode: 'KJFK',
      name: 'John F. Kennedy International Airport',
      city: 'New York',
      state: 'New York',
      country: 'United States',
      countryCode: 'US',
      region: 'North America',
      continent: 'North America',
      latitude: 40.639751,
      longitude: -73.778925,
      timezone: 'America/New_York',
      isInternational: true,
      popularityScore: 98,
      alternativeAirports: ['LGA', 'EWR'],
    },
    {
      iataCode: 'LAX',
      icaoCode: 'KLAX',
      name: 'Los Angeles International Airport',
      city: 'Los Angeles',
      state: 'California',
      country: 'United States',
      countryCode: 'US',
      region: 'North America',
      continent: 'North America',
      latitude: 33.941589,
      longitude: -118.40853,
      timezone: 'America/Los_Angeles',
      isInternational: true,
      popularityScore: 99,
      alternativeAirports: ['BUR', 'LGB'],
    },
    {
      iataCode: 'CUN',
      icaoCode: 'MMUN',
      name: 'Aeropuerto Internacional de Cancún',
      city: 'Cancún',
      country: 'México',
      countryCode: 'MX',
      region: 'North America',
      continent: 'North America',
      latitude: 21.036528,
      longitude: -86.876808,
      timezone: 'America/Cancun',
      isInternational: true,
      popularityScore: 94,
      alternativeAirports: [],
    },
    {
      iataCode: 'YVR',
      icaoCode: 'CYVR',
      name: 'Vancouver International Airport',
      city: 'Vancouver',
      state: 'British Columbia',
      country: 'Canada',
      countryCode: 'CA',
      region: 'North America',
      continent: 'North America',
      latitude: 49.196691,
      longitude: -123.181512,
      timezone: 'America/Vancouver',
      isInternational: true,
      popularityScore: 90,
      alternativeAirports: [],
    },

    // Europa
    {
      iataCode: 'LIS',
      icaoCode: 'LPPT',
      name: 'Aeroporto de Lisboa Humberto Delgado',
      city: 'Lisboa',
      country: 'Portugal',
      countryCode: 'PT',
      region: 'Southern Europe',
      continent: 'Europe',
      latitude: 38.781311,
      longitude: -9.135919,
      timezone: 'Europe/Lisbon',
      isInternational: true,
      popularityScore: 89,
      alternativeAirports: [],
    },
    {
      iataCode: 'CDG',
      icaoCode: 'LFPG',
      name: 'Aéroport Paris-Charles de Gaulle',
      city: 'Paris',
      country: 'France',
      countryCode: 'FR',
      region: 'Western Europe',
      continent: 'Europe',
      latitude: 49.012779,
      longitude: 2.55,
      timezone: 'Europe/Paris',
      isInternational: true,
      popularityScore: 97,
      alternativeAirports: ['ORY'],
    },
    {
      iataCode: 'MAD',
      icaoCode: 'LEMD',
      name: 'Aeropuerto Adolfo Suárez Madrid-Barajas',
      city: 'Madrid',
      country: 'Spain',
      countryCode: 'ES',
      region: 'Southern Europe',
      continent: 'Europe',
      latitude: 40.471926,
      longitude: -3.56264,
      timezone: 'Europe/Madrid',
      isInternational: true,
      popularityScore: 86,
      alternativeAirports: [],
    },
    {
      iataCode: 'BCN',
      icaoCode: 'LEBL',
      name: 'Aeropuerto de Barcelona-El Prat',
      city: 'Barcelona',
      country: 'Spain',
      countryCode: 'ES',
      region: 'Southern Europe',
      continent: 'Europe',
      latitude: 41.297078,
      longitude: 2.078464,
      timezone: 'Europe/Madrid',
      isInternational: true,
      popularityScore: 87,
      alternativeAirports: [],
    },
    {
      iataCode: 'FCO',
      icaoCode: 'LIRF',
      name: 'Aeroporto di Roma-Fiumicino',
      city: 'Rome',
      country: 'Italy',
      countryCode: 'IT',
      region: 'Southern Europe',
      continent: 'Europe',
      latitude: 41.804475,
      longitude: 12.250797,
      timezone: 'Europe/Rome',
      isInternational: true,
      popularityScore: 88,
      alternativeAirports: ['CIA'],
    },
    {
      iataCode: 'MXP',
      icaoCode: 'LIMC',
      name: 'Aeroporto di Milano-Malpensa',
      city: 'Milan',
      country: 'Italy',
      countryCode: 'IT',
      region: 'Southern Europe',
      continent: 'Europe',
      latitude: 45.630606,
      longitude: 8.728111,
      timezone: 'Europe/Rome',
      isInternational: true,
      popularityScore: 83,
      alternativeAirports: ['LIN'],
    },
    {
      iataCode: 'FRA',
      icaoCode: 'EDDF',
      name: 'Flughafen Frankfurt am Main',
      city: 'Frankfurt',
      country: 'Germany',
      countryCode: 'DE',
      region: 'Western Europe',
      continent: 'Europe',
      latitude: 50.033333,
      longitude: 8.570556,
      timezone: 'Europe/Berlin',
      isInternational: true,
      popularityScore: 90,
      alternativeAirports: [],
    },
    {
      iataCode: 'DUB',
      icaoCode: 'EIDW',
      name: 'Dublin Airport',
      city: 'Dublin',
      country: 'Ireland',
      countryCode: 'IE',
      region: 'Northern Europe',
      continent: 'Europe',
      latitude: 53.421333,
      longitude: -6.270075,
      timezone: 'Europe/Dublin',
      isInternational: true,
      popularityScore: 79,
      alternativeAirports: [],
    },

    // Ásia e Oriente Médio
    {
      iataCode: 'NRT',
      icaoCode: 'RJAA',
      name: 'Narita International Airport',
      city: 'Narita',
      country: 'Japão',
      countryCode: 'JP',
      region: 'Asia',
      continent: 'Asia',
      latitude: 35.764722,
      longitude: 140.386389,
      timezone: 'Asia/Tokyo',
      isInternational: true,
      popularityScore: 95,
      alternativeAirports: ['HND'],
    },
    {
      iataCode: 'DXB',
      icaoCode: 'OMDB',
      name: 'Dubai International Airport',
      city: 'Dubai',
      country: 'Emirados Árabes Unidos',
      countryCode: 'AE',
      region: 'Middle East',
      continent: 'Asia',
      latitude: 25.253174,
      longitude: 55.365673,
      timezone: 'Asia/Dubai',
      isInternational: true,
      popularityScore: 99,
      alternativeAirports: ['DWC'],
    },
    {
      iataCode: 'DPS',
      icaoCode: 'WADD',
      name: 'Ngurah Rai International Airport',
      city: 'Denpasar',
      country: 'Indonésia',
      countryCode: 'ID',
      region: 'Southeast Asia',
      continent: 'Asia',
      latitude: -8.748056,
      longitude: 115.167500,
      timezone: 'Asia/Makassar',
      isInternational: true,
      popularityScore: 88,
      alternativeAirports: [],
    },

    // África
    {
      iataCode: 'CPT',
      icaoCode: 'FACT',
      name: 'Cape Town International Airport',
      city: 'Cidade do Cabo',
      country: 'África do Sul',
      countryCode: 'ZA',
      region: 'Southern Africa',
      continent: 'Africa',
      latitude: -33.964806,
      longitude: 18.601667,
      timezone: 'Africa/Johannesburg',
      isInternational: true,
      popularityScore: 90,
      alternativeAirports: [],
    },
    {
      iataCode: 'RAK',
      icaoCode: 'GMMX',
      name: 'Marrakesh Menara Airport',
      city: 'Marrakesh',
      country: 'Marrocos',
      countryCode: 'MA',
      region: 'North Africa',
      continent: 'Africa',
      latitude: 31.608611,
      longitude: -8.036667,
      timezone: 'Africa/Casablanca',
      isInternational: true,
      popularityScore: 82,
      alternativeAirports: [],
    },

    // Oceania
    {
      iataCode: 'SYD',
      icaoCode: 'YSSY',
      name: 'Sydney Kingsford Smith Airport',
      city: 'Sydney',
      country: 'Austrália',
      countryCode: 'AU',
      region: 'Oceania',
      continent: 'Oceania',
      latitude: -33.939922,
      longitude: 151.175276,
      timezone: 'Australia/Sydney',
      isInternational: true,
      popularityScore: 96,
      alternativeAirports: [],
    },
    {
      iataCode: 'ZQN',
      icaoCode: 'NZQN',
      name: 'Queenstown Airport',
      city: 'Queenstown',
      country: 'Nova Zelândia',
      countryCode: 'NZ',
      region: 'Oceania',
      continent: 'Oceania',
      latitude: -45.021110,
      longitude: 168.739182,
      timezone: 'Pacific/Auckland',
      isInternational: true,
      popularityScore: 80,
      alternativeAirports: ['DUD'],
    },

    // Caribe
    {
      iataCode: 'PUJ',
      icaoCode: 'MDPC',
      name: 'Punta Cana International Airport',
      city: 'Punta Cana',
      country: 'Dominican Republic',
      countryCode: 'DO',
      region: 'Caribbean',
      continent: 'North America',
      latitude: 18.567367,
      longitude: -68.363431,
      timezone: 'America/Santo_Domingo',
      isInternational: true,
      popularityScore: 77,
      alternativeAirports: [],
    },
    {
      iataCode: 'CUR',
      icaoCode: 'TNCC',
      name: 'Curaçao International Airport',
      city: 'Willemstad',
      country: 'Curaçao',
      countryCode: 'CW',
      region: 'Caribbean',
      continent: 'North America',
      latitude: 12.188853,
      longitude: -68.959803,
      timezone: 'America/Curacao',
      isInternational: true,
      popularityScore: 73,
      alternativeAirports: [],
    },
  ];

  for (const airport of airports) {
    await prisma.airport.upsert({
      where: { iataCode: airport.iataCode },
      update: airport,
      create: airport,
    });
  }

  console.log(`✅ Created ${airports.length} airports`);
}
