import { PrismaClient } from '../../src/generated/prisma';

export async function seedDestinations(prisma: PrismaClient) {
  console.log('🌍 Seeding destinations...');

  const destinations = [
    // Brasil - Destinos Nacionais
    {
      name: 'São Paulo',
      city: 'São Paulo',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'A maior metrópole da América do Sul, São Paulo é um centro financeiro, cultural e gastronômico. Oferece uma vida noturna vibrante, museus de classe mundial, restaurantes premiados e uma diversidade cultural incomparável.',
      shortDescription: 'Metrópole vibrante com gastronomia de classe mundial',
      bestMonths: [3, 4, 5, 8, 9, 10],
      averageBudget: 350.00,
      popularityScore: 100,
      latitude: -23.550520,
      longitude: -46.633308,
      timezone: 'America/Sao_Paulo',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico'],
    },
    {
      name: 'Rio de Janeiro',
      city: 'Rio de Janeiro',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'A Cidade Maravilhosa encanta com suas praias icônicas, o Cristo Redentor, o Pão de Açúcar e o Carnaval mais famoso do mundo. Combina beleza natural com vida urbana intensa.',
      shortDescription: 'Praias icônicas, Cristo Redentor e Carnaval',
      bestMonths: [1, 2, 3, 9, 10, 11, 12],
      averageBudget: 400.00,
      popularityScore: 98,
      latitude: -22.906847,
      longitude: -43.172896,
      timezone: 'America/Sao_Paulo',
      categoryNames: ['Praia', 'Metrópole', 'Cultural', 'Romance'],
    },
    {
      name: 'Salvador',
      city: 'Salvador',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Capital da Bahia, Salvador é o coração da cultura afro-brasileira. O Pelourinho, com sua arquitetura colonial, praias paradisíacas e culinária baiana fazem da cidade um destino único.',
      shortDescription: 'Cultura afro-brasileira e praias paradisíacas',
      bestMonths: [1, 2, 3, 9, 10, 11, 12],
      averageBudget: 300.00,
      popularityScore: 85,
      latitude: -12.977749,
      longitude: -38.501630,
      timezone: 'America/Bahia',
      categoryNames: ['Praia', 'Cidade Histórica', 'Cultural', 'Gastronômico'],
    },
    {
      name: 'Recife e Porto de Galinhas',
      city: 'Recife',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Recife, a Veneza Brasileira, combina história, cultura e praias urbanas. Porto de Galinhas, a 60km, oferece piscinas naturais cristalinas e é uma das praias mais famosas do Brasil.',
      shortDescription: 'Piscinas naturais e cultura pernambucana',
      bestMonths: [1, 2, 3, 9, 10, 11, 12],
      averageBudget: 280.00,
      popularityScore: 88,
      latitude: -8.047562,
      longitude: -34.876966,
      timezone: 'America/Recife',
      categoryNames: ['Praia', 'Cultural', 'Família'],
    },
    {
      name: 'Fortaleza',
      city: 'Fortaleza',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Capital do Ceará, conhecida por suas praias urbanas movimentadas, o Beach Park e proximidade com praias paradisíacas como Jericoacoara e Canoa Quebrada.',
      shortDescription: 'Praias urbanas e parques aquáticos',
      bestMonths: [1, 2, 7, 8, 9, 10, 11, 12],
      averageBudget: 270.00,
      popularityScore: 82,
      latitude: -3.731862,
      longitude: -38.526670,
      timezone: 'America/Fortaleza',
      categoryNames: ['Praia', 'Família', 'Aventura'],
    },
    {
      name: 'Florianópolis',
      city: 'Florianópolis',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'A Ilha da Magia possui mais de 40 praias, desde as tranquilas para famílias até as agitadas para surfistas. Combina natureza exuberante com boa infraestrutura.',
      shortDescription: 'Ilha com mais de 40 praias paradisíacas',
      bestMonths: [1, 2, 3, 11, 12],
      averageBudget: 320.00,
      popularityScore: 86,
      latitude: -27.594870,
      longitude: -48.548220,
      timezone: 'America/Sao_Paulo',
      categoryNames: ['Praia', 'Natureza', 'Aventura', 'Família'],
    },
    {
      name: 'Foz do Iguaçu',
      city: 'Foz do Iguaçu',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Lar das Cataratas do Iguaçu, uma das maiores quedas d\'água do mundo. Oferece também o Parque das Aves, a Usina de Itaipu e proximidade com Argentina e Paraguai.',
      shortDescription: 'Cataratas do Iguaçu e maravilhas naturais',
      bestMonths: [3, 4, 5, 8, 9, 10],
      averageBudget: 290.00,
      popularityScore: 84,
      latitude: -25.516389,
      longitude: -54.585556,
      timezone: 'America/Sao_Paulo',
      categoryNames: ['Natureza', 'Aventura', 'Família'],
    },

    // América do Sul
    {
      name: 'Buenos Aires',
      city: 'Buenos Aires',
      country: 'Argentina',
      countryCode: 'AR',
      description: 'A Paris da América do Sul encanta com seus bairros charmosos, tango, arquitetura europeia e gastronomia excepcional. San Telmo, Palermo e La Boca são imperdíveis.',
      shortDescription: 'Tango, gastronomia e arquitetura europeia',
      bestMonths: [3, 4, 5, 9, 10, 11],
      averageBudget: 450.00,
      popularityScore: 95,
      latitude: -34.603722,
      longitude: -58.381592,
      timezone: 'America/Argentina/Buenos_Aires',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico', 'Romance'],
    },
    {
      name: 'Santiago',
      city: 'Santiago',
      country: 'Chile',
      countryCode: 'CL',
      description: 'Capital do Chile, aos pés da Cordilheira dos Andes. Oferece excelente gastronomia, vinícolas renomadas nos arredores e fácil acesso a ski resorts e praias.',
      shortDescription: 'Cordilheira dos Andes e vinícolas premiadas',
      bestMonths: [3, 4, 5, 9, 10, 11],
      averageBudget: 420.00,
      popularityScore: 93,
      latitude: -33.448890,
      longitude: -70.669265,
      timezone: 'America/Santiago',
      categoryNames: ['Metrópole', 'Gastronômico', 'Aventura'],
    },
    {
      name: 'Lima',
      city: 'Lima',
      country: 'Peru',
      countryCode: 'PE',
      description: 'Capital gastronômica da América do Sul, Lima combina história colonial com culinária de classe mundial. Porta de entrada para Machu Picchu.',
      shortDescription: 'Capital gastronômica e história milenar',
      bestMonths: [1, 2, 3, 11, 12],
      averageBudget: 380.00,
      popularityScore: 87,
      latitude: -12.046374,
      longitude: -77.042793,
      timezone: 'America/Lima',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico', 'Cidade Histórica'],
    },
    {
      name: 'Cusco e Machu Picchu',
      city: 'Cusco',
      country: 'Peru',
      countryCode: 'PE',
      description: 'Antiga capital do Império Inca, Cusco é a porta de entrada para Machu Picchu, uma das Sete Maravilhas do Mundo Moderno. Oferece história milenar e paisagens deslumbrantes.',
      shortDescription: 'Machu Picchu e legado Inca',
      bestMonths: [4, 5, 6, 7, 8, 9, 10],
      averageBudget: 500.00,
      popularityScore: 92,
      latitude: -13.531950,
      longitude: -71.967463,
      timezone: 'America/Lima',
      categoryNames: ['Montanha', 'Cidade Histórica', 'Cultural', 'Aventura'],
    },
    {
      name: 'Montevidéu',
      city: 'Montevidéu',
      country: 'Uruguay',
      countryCode: 'UY',
      description: 'Capital tranquila do Uruguai, oferece arquitetura colonial, praias urbanas, mercados tradicionais e a famosa Ciudad Vieja. Próxima a Punta del Este.',
      shortDescription: 'Charme colonial e praias tranquilas',
      bestMonths: [1, 2, 3, 11, 12],
      averageBudget: 360.00,
      popularityScore: 75,
      latitude: -34.901112,
      longitude: -56.164532,
      timezone: 'America/Montevideo',
      categoryNames: ['Metrópole', 'Cidade Histórica', 'Praia'],
    },
    {
      name: 'Cartagena',
      city: 'Cartagena',
      country: 'Colombia',
      countryCode: 'CO',
      description: 'Cidade murada no Caribe colombiano, com arquitetura colonial preservada, praias paradisíacas e vida noturna vibrante. Patrimônio Mundial da UNESCO.',
      shortDescription: 'Cidade murada e Caribe colombiano',
      bestMonths: [1, 2, 3, 12],
      averageBudget: 400.00,
      popularityScore: 81,
      latitude: 10.391049,
      longitude: -75.479426,
      timezone: 'America/Bogota',
      categoryNames: ['Praia', 'Cidade Histórica', 'Cultural', 'Romance'],
    },

    // América do Norte
    {
      name: 'Miami',
      city: 'Miami',
      country: 'United States',
      countryCode: 'US',
      description: 'Cidade cosmopolita da Flórida, famosa por suas praias, vida noturna, compras e arquitetura Art Déco em South Beach. Porta de entrada para cruzeiros no Caribe.',
      shortDescription: 'Praias, compras e vida noturna em South Beach',
      bestMonths: [1, 2, 3, 4, 11, 12],
      averageBudget: 800.00,
      popularityScore: 94,
      latitude: 25.761680,
      longitude: -80.191790,
      timezone: 'America/New_York',
      categoryNames: ['Praia', 'Metrópole', 'Compras', 'Luxo'],
    },
    {
      name: 'Orlando',
      city: 'Orlando',
      country: 'United States',
      countryCode: 'US',
      description: 'Capital mundial dos parques temáticos, abriga Walt Disney World, Universal Studios e SeaWorld. Destino perfeito para famílias.',
      shortDescription: 'Capital mundial dos parques temáticos',
      bestMonths: [1, 2, 3, 4, 5, 10, 11, 12],
      averageBudget: 900.00,
      popularityScore: 91,
      latitude: 28.538336,
      longitude: -81.379234,
      timezone: 'America/New_York',
      categoryNames: ['Família', 'Aventura'],
    },
    {
      name: 'Nova York',
      city: 'New York',
      country: 'United States',
      countryCode: 'US',
      description: 'A cidade que nunca dorme oferece museus icônicos, Broadway, arranha-céus, compras na 5ª Avenida, Central Park e uma diversidade cultural incomparável.',
      shortDescription: 'Broadway, arranha-céus e diversidade cultural',
      bestMonths: [4, 5, 6, 9, 10],
      averageBudget: 1200.00,
      popularityScore: 98,
      latitude: 40.712776,
      longitude: -74.005974,
      timezone: 'America/New_York',
      categoryNames: ['Metrópole', 'Cultural', 'Compras', 'Luxo'],
    },
    {
      name: 'São Francisco',
      city: 'San Francisco',
      country: 'United States',
      countryCode: 'US',
      description: 'São Francisco encanta com a Golden Gate Bridge, bairros icônicos como Fisherman\'s Wharf e Mission District, tecnologia no Vale do Silício e gastronomia sofisticada.',
      shortDescription: 'Golden Gate, tecnologia e gastronomia californiana',
      bestMonths: [4, 5, 9, 10],
      averageBudget: 1100.00,
      popularityScore: 92,
      latitude: 37.774929,
      longitude: -122.419418,
      timezone: 'America/Los_Angeles',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico', 'Compras'],
    },

    // Europa
    {
      name: 'Lisboa',
      city: 'Lisboa',
      country: 'Portugal',
      countryCode: 'PT',
      description: 'Capital portuguesa encanta com seus azulejos, bondes históricos, fado, pastéis de Belém e vistas panorâmicas. Clima ameno e custo acessível para a Europa.',
      shortDescription: 'Azulejos, fado e gastronomia portuguesa',
      bestMonths: [4, 5, 6, 9, 10],
      averageBudget: 600.00,
      popularityScore: 89,
      latitude: 38.722252,
      longitude: -9.139337,
      timezone: 'Europe/Lisbon',
      categoryNames: ['Metrópole', 'Cidade Histórica', 'Cultural', 'Gastronômico'],
    },
    {
      name: 'Paris',
      city: 'Paris',
      country: 'France',
      countryCode: 'FR',
      description: 'A Cidade Luz é sinônimo de romance, arte e gastronomia. Torre Eiffel, Louvre, Champs-Élysées e cafés charmosos fazem de Paris um destino atemporal.',
      shortDescription: 'Cidade do romance, arte e gastronomia',
      bestMonths: [4, 5, 6, 9, 10],
      averageBudget: 1000.00,
      popularityScore: 97,
      latitude: 48.856613,
      longitude: 2.352222,
      timezone: 'Europe/Paris',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico', 'Romance', 'Luxo'],
    },
    {
      name: 'Roma',
      city: 'Rome',
      country: 'Italy',
      countryCode: 'IT',
      description: 'A Cidade Eterna abriga o Coliseu, Vaticano, Fontana di Trevi e ruínas milenares. Combina história antiga com gastronomia italiana autêntica.',
      shortDescription: 'Coliseu, Vaticano e história milenar',
      bestMonths: [4, 5, 6, 9, 10],
      averageBudget: 850.00,
      popularityScore: 88,
      latitude: 41.902782,
      longitude: 12.496366,
      timezone: 'Europe/Rome',
      categoryNames: ['Metrópole', 'Cidade Histórica', 'Cultural', 'Gastronômico'],
    },
    {
      name: 'Barcelona',
      city: 'Barcelona',
      country: 'Spain',
      countryCode: 'ES',
      description: 'Capital catalã combina praias urbanas, arquitetura de Gaudí (Sagrada Família), gastronomia excepcional e vida noturna vibrante.',
      shortDescription: 'Gaudí, praias e gastronomia catalã',
      bestMonths: [5, 6, 9, 10],
      averageBudget: 750.00,
      popularityScore: 87,
      latitude: 41.385064,
      longitude: 2.173404,
      timezone: 'Europe/Madrid',
      categoryNames: ['Metrópole', 'Praia', 'Cultural', 'Gastronômico'],
    },
    {
      name: 'Madrid',
      city: 'Madrid',
      country: 'Spain',
      countryCode: 'ES',
      description: 'Capital espanhola oferece museus de classe mundial (Prado, Reina Sofía), parques encantadores, tapas deliciosas e vida noturna agitada.',
      shortDescription: 'Museus de arte e tapas espanholas',
      bestMonths: [4, 5, 6, 9, 10],
      averageBudget: 700.00,
      popularityScore: 86,
      latitude: 40.416775,
      longitude: -3.703790,
      timezone: 'Europe/Madrid',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico'],
    },

    // Caribe
    {
      name: 'Punta Cana',
      city: 'Punta Cana',
      country: 'Dominican Republic',
      countryCode: 'DO',
      description: 'Paraíso caribenho com resorts all-inclusive, praias de areia branca, águas cristalinas e atividades aquáticas. Ideal para lua de mel e famílias.',
      shortDescription: 'Resorts all-inclusive e praias caribenhas',
      bestMonths: [1, 2, 3, 4, 11, 12],
      averageBudget: 700.00,
      popularityScore: 83,
      latitude: 18.581812,
      longitude: -68.404502,
      timezone: 'America/Santo_Domingo',
      categoryNames: ['Praia', 'Romance', 'Família', 'Luxo'],
    },
    {
      name: 'Curaçao',
      city: 'Willemstad',
      country: 'Curaçao',
      countryCode: 'CW',
      description: 'Ilha caribenha holandesa com arquitetura colorida, praias paradisíacas, mergulho de classe mundial e cultura multicultural única.',
      shortDescription: 'Arquitetura colorida e mergulho caribenho',
      bestMonths: [1, 2, 3, 4, 5, 12],
      averageBudget: 650.00,
      popularityScore: 78,
      latitude: 12.122422,
      longitude: -68.882423,
      timezone: 'America/Curacao',
      categoryNames: ['Praia', 'Aventura', 'Cultural'],
    },
  ];

  for (const dest of destinations) {
    const { categoryNames, ...destData } = dest;

    // Check if destination already exists
    const existing = await prisma.destination.findFirst({
      where: {
        name: destData.name,
        city: destData.city,
        country: destData.country
      }
    });

    const destination = existing
      ? await prisma.destination.update({
          where: { id: existing.id },
          data: destData
        })
      : await prisma.destination.create({
          data: destData
        });

    // Link categories
    for (const categoryName of categoryNames) {
      const category = await prisma.category.findFirst({
        where: { name: categoryName }
      });

      if (category) {
        await prisma.destinationCategory.upsert({
          where: {
            destinationId_categoryId: {
              destinationId: destination.id,
              categoryId: category.id
            }
          },
          update: {},
          create: {
            destinationId: destination.id,
            categoryId: category.id
          }
        });
      }
    }
  }

  console.log(`✅ Created ${destinations.length} destinations`);
}
