import { PrismaClient } from '../../src/generated/prisma';

export async function seedDestinations(prisma: PrismaClient) {
  console.log('🌍 Seeding destinations...');

  const defaultDestinationGallery = [
    'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
  ];

  const destinationMedia: Record<string, { heroImageUrl: string; galleryImageUrls: string[] }> = {
    'São Paulo': {
      heroImageUrl: 'https://images.unsplash.com/photo-1531256456869-ce942a665e80?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    'Rio de Janeiro': {
      heroImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Salvador: {
      heroImageUrl: 'https://images.unsplash.com/photo-1526404079166-6c3b14d4446f?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    'Recife e Porto de Galinhas': {
      heroImageUrl: 'https://images.unsplash.com/photo-1518458028785-8fbcd101ebb9?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Fortaleza: {
      heroImageUrl: 'https://images.unsplash.com/photo-1526402468770-3b30f66e187d?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Florianópolis: {
      heroImageUrl: 'https://images.unsplash.com/photo-1543076447-215ad9ba6923?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    'Foz do Iguaçu': {
      heroImageUrl: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    'Buenos Aires': {
      heroImageUrl: 'https://images.unsplash.com/photo-1529307474719-3d1d1cfbb0de?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Santiago: {
      heroImageUrl: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Lima: {
      heroImageUrl: 'https://images.unsplash.com/photo-1520975918316-7da8f9f86006?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    'Cusco e Machu Picchu': {
      heroImageUrl: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Montevidéu: {
      heroImageUrl: 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Cartagena: {
      heroImageUrl: 'https://images.unsplash.com/photo-1543248939-ff40856f65d4?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Miami: {
      heroImageUrl: 'https://images.unsplash.com/photo-1464146072230-91cabc968266?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Orlando: {
      heroImageUrl: 'https://images.unsplash.com/photo-1505843513577-22bb7d21e455?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    'Nova York': {
      heroImageUrl: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    'São Francisco': {
      heroImageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Lisboa: {
      heroImageUrl: 'https://images.unsplash.com/photo-1508641898614-8c317d46054b?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Paris: {
      heroImageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Roma: {
      heroImageUrl: 'https://images.unsplash.com/photo-1526481280695-3c469ccf26a4?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Barcelona: {
      heroImageUrl: 'https://images.unsplash.com/photo-1473959383413-cd1bf1ac1b77?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Madrid: {
      heroImageUrl: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    'Punta Cana': {
      heroImageUrl: 'https://images.unsplash.com/photo-1478118330274-ff72cf1161f3?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Curaçao: {
      heroImageUrl: 'https://images.unsplash.com/photo-1543342386-8b95db76a05f?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultDestinationGallery],
    },
    Gramado: {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?gramado,brazil',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?serra-gaucha',
        'https://source.unsplash.com/1200x800/?gramado,natal-luz',
      ],
    },
    Jericoacoara: {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?jericoacoara,beach',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?jeri,dunes',
        'https://source.unsplash.com/1200x800/?jericoacoara,sunset',
      ],
    },
    'Fernando de Noronha': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?fernando+de+noronha,brazil',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?noronha,beach',
        'https://source.unsplash.com/1200x800/?noronha,diving',
      ],
    },
    Bonito: {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?bonito,brazil',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?bonito,river',
        'https://source.unsplash.com/1200x800/?bonito,cave',
      ],
    },
    'Manaus e Amazônia': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?amazon,rainforest',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?manaus,river',
        'https://source.unsplash.com/1200x800/?amazon,waterfall',
      ],
    },
    'Lençóis Maranhenses': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?lencois,maranhenses',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?lencois,dunes',
        'https://source.unsplash.com/1200x800/?barreirinhas,lagoa',
      ],
    },
    'Cancún': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?cancun,resort',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?riviera,maya',
        'https://source.unsplash.com/1200x800/?tulum,beach',
      ],
    },
    'Los Angeles': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?los+angeles,skyline',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?santa+monica,pier',
        'https://source.unsplash.com/1200x800/?hollywood,sign',
      ],
    },
    Vancouver: {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?vancouver,canada',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?stanley+park',
        'https://source.unsplash.com/1200x800/?vancouver,mountains',
      ],
    },
    'Tóquio': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?tokyo,city',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?shibuya,crossing',
        'https://source.unsplash.com/1200x800/?tokyo,temple',
      ],
    },
    Dubai: {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?dubai,skyline',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?dubai,desert',
        'https://source.unsplash.com/1200x800/?burj,khalifa',
      ],
    },
    'Bali (Seminyak e Ubud)': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?bali,indonesia',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?bali,rice+terrace',
        'https://source.unsplash.com/1200x800/?bali,temple',
      ],
    },
    'Cidade do Cabo': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?cape+town,table+mountain',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?cape+town,beach',
        'https://source.unsplash.com/1200x800/?stellenbosch,winery',
      ],
    },
    Sydney: {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?sydney,opera+house',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?sydney,harbour',
        'https://source.unsplash.com/1200x800/?bondi,beach',
      ],
    },
    Queenstown: {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?queenstown,new+zealand',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?queenstown,lake',
        'https://source.unsplash.com/1200x800/?new+zealand,alps',
      ],
    },
    Marrakesh: {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?marrakech,medina',
      galleryImageUrls: [
        'https://source.unsplash.com/1200x800/?marrakech,souk',
        'https://source.unsplash.com/1200x800/?marrakech,riad',
      ],
    },
  };

  const destinations = [
    // Brasil - Destinos Nacionais
    {
      name: 'São Paulo',
      city: 'São Paulo',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'A maior metrópole da América do Sul, São Paulo é um centro financeiro, cultural e gastronômico. Oferece uma vida noturna vibrante, museus de classe mundial, restaurantes premiados e uma diversidade cultural incomparável.',
      shortDescription: 'Metrópole vibrante com gastronomia de classe mundial',
      bestMonths: [3, 4, 5, 8, 9, 10],
      averageBudget: 350.00,
      popularityScore: 100,
      latitude: -23.550520,
      longitude: -46.633308,
      timezone: 'America/Sao_Paulo',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico'],
    },
    {
      name: 'Rio de Janeiro',
      city: 'Rio de Janeiro',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'A Cidade Maravilhosa encanta com suas praias icônicas, o Cristo Redentor, o Pão de Açúcar e o Carnaval mais famoso do mundo. Combina beleza natural com vida urbana intensa.',
      shortDescription: 'Praias icônicas, Cristo Redentor e Carnaval',
      bestMonths: [1, 2, 3, 9, 10, 11, 12],
      averageBudget: 400.00,
      popularityScore: 98,
      latitude: -22.906847,
      longitude: -43.172896,
      timezone: 'America/Sao_Paulo',
      categoryNames: ['Praia', 'Metrópole', 'Cultural', 'Romance'],
    },
    {
      name: 'Salvador',
      city: 'Salvador',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Capital da Bahia, Salvador é o coração da cultura afro-brasileira. O Pelourinho, com sua arquitetura colonial, praias paradisíacas e culinária baiana fazem da cidade um destino único.',
      shortDescription: 'Cultura afro-brasileira e praias paradisíacas',
      bestMonths: [1, 2, 3, 9, 10, 11, 12],
      averageBudget: 300.00,
      popularityScore: 85,
      latitude: -12.977749,
      longitude: -38.501630,
      timezone: 'America/Bahia',
      categoryNames: ['Praia', 'Cidade Histórica', 'Cultural', 'Gastronômico'],
    },
    {
      name: 'Recife e Porto de Galinhas',
      city: 'Recife',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Recife, a Veneza Brasileira, combina história, cultura e praias urbanas. Porto de Galinhas, a 60km, oferece piscinas naturais cristalinas e é uma das praias mais famosas do Brasil.',
      shortDescription: 'Piscinas naturais e cultura pernambucana',
      bestMonths: [1, 2, 3, 9, 10, 11, 12],
      averageBudget: 280.00,
      popularityScore: 88,
      latitude: -8.047562,
      longitude: -34.876966,
      timezone: 'America/Recife',
      categoryNames: ['Praia', 'Cultural', 'Família'],
    },
    {
      name: 'Fortaleza',
      city: 'Fortaleza',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Capital do Ceará, conhecida por suas praias urbanas movimentadas, o Beach Park e proximidade com praias paradisíacas como Jericoacoara e Canoa Quebrada.',
      shortDescription: 'Praias urbanas e parques aquáticos',
      bestMonths: [1, 2, 7, 8, 9, 10, 11, 12],
      averageBudget: 270.00,
      popularityScore: 82,
      latitude: -3.731862,
      longitude: -38.526670,
      timezone: 'America/Fortaleza',
      categoryNames: ['Praia', 'Família', 'Aventura'],
    },
    {
      name: 'Florianópolis',
      city: 'Florianópolis',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'A Ilha da Magia possui mais de 40 praias, desde as tranquilas para famílias até as agitadas para surfistas. Combina natureza exuberante com boa infraestrutura.',
      shortDescription: 'Ilha com mais de 40 praias paradisíacas',
      bestMonths: [1, 2, 3, 11, 12],
      averageBudget: 320.00,
      popularityScore: 86,
      latitude: -27.594870,
      longitude: -48.548220,
      timezone: 'America/Sao_Paulo',
      categoryNames: ['Praia', 'Natureza', 'Aventura', 'Família'],
    },
    {
      name: 'Foz do Iguaçu',
      city: 'Foz do Iguaçu',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Lar das Cataratas do Iguaçu, uma das maiores quedas d\'água do mundo. Oferece também o Parque das Aves, a Usina de Itaipu e proximidade com Argentina e Paraguai.',
      shortDescription: 'Cataratas do Iguaçu e maravilhas naturais',
      bestMonths: [3, 4, 5, 8, 9, 10],
      averageBudget: 290.00,
      popularityScore: 84,
      latitude: -25.516389,
      longitude: -54.585556,
      timezone: 'America/Sao_Paulo',
      categoryNames: ['Natureza', 'Aventura', 'Família'],
    },
    {
      name: 'Gramado',
      city: 'Gramado',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Clima europeu na Serra Gaúcha com o famoso Natal Luz, chocolaterias artesanais, vinícolas vizinhas e parques temáticos para toda a família.',
      shortDescription: 'Serra Gaúcha com clima europeu e Natal Luz',
      bestMonths: [5, 6, 7, 8, 11, 12],
      averageBudget: 420.00,
      popularityScore: 83,
      latitude: -29.378000,
      longitude: -50.873000,
      timezone: 'America/Sao_Paulo',
      categoryNames: ['Família', 'Cultural', 'Romance', 'Gastronômico'],
    },
    {
      name: 'Jericoacoara',
      city: 'Jijoca de Jericoacoara',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Vilarejo praiano cercado por dunas, lagoas cristalinas e ventos perfeitos para kitesurf. Pôr do sol nas dunas e a Pedra Furada são cartões-postais inesquecíveis.',
      shortDescription: 'Dunas, lagoas e pôr do sol inesquecível',
      bestMonths: [7, 8, 9, 10, 11, 12],
      averageBudget: 450.00,
      popularityScore: 85,
      latitude: -2.798775,
      longitude: -40.512220,
      timezone: 'America/Fortaleza',
      categoryNames: ['Praia', 'Natureza', 'Aventura'],
    },
    {
      name: 'Fernando de Noronha',
      city: 'Fernando de Noronha',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Arquipélago paradisíaco com praias desertas, vida marinha abundante e controle de visitantes. Ideal para mergulho, trilhas e experiências românticas em meio à natureza preservada.',
      shortDescription: 'Arquipélago preservado com mergulho de classe mundial',
      bestMonths: [8, 9, 10, 11, 12, 1, 2],
      averageBudget: 950.00,
      popularityScore: 90,
      latitude: -3.857600,
      longitude: -32.429700,
      timezone: 'America/Noronha',
      categoryNames: ['Praia', 'Natureza', 'Aventura', 'Romance', 'Luxo'],
    },
    {
      name: 'Bonito',
      city: 'Bonito',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Capital do ecoturismo brasileiro, Bonito oferece rios de águas cristalinas para flutuação, cavernas, cachoeiras e gastronomia pantaneira.',
      shortDescription: 'Flutuação em rios cristalinos e cavernas azuis',
      bestMonths: [4, 5, 6, 7, 8, 9],
      averageBudget: 380.00,
      popularityScore: 82,
      latitude: -21.126100,
      longitude: -56.483600,
      timezone: 'America/Campo_Grande',
      categoryNames: ['Natureza', 'Aventura', 'Família'],
    },
    {
      name: 'Manaus e Amazônia',
      city: 'Manaus',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Porta de entrada para a Floresta Amazônica, com hotéis de selva, encontro das águas, mercados históricos e experiências culturais com comunidades ribeirinhas.',
      shortDescription: 'Floresta Amazônica, rios poderosos e cultura ribeirinha',
      bestMonths: [6, 7, 8, 9, 10],
      averageBudget: 550.00,
      popularityScore: 84,
      latitude: -3.119027,
      longitude: -60.021731,
      timezone: 'America/Manaus',
      categoryNames: ['Natureza', 'Aventura', 'Cultural'],
    },
    {
      name: 'Lençóis Maranhenses',
      city: 'Barreirinhas',
      country: 'Brasil',
      countryCode: 'BR',
      description: 'Parque Nacional com dunas branquinhas e lagoas de água doce que se formam no período chuvoso. Passeios de 4x4, voos panorâmicos e vilas rústicas completam o roteiro.',
      shortDescription: 'Dunas e lagoas cristalinas no Nordeste brasileiro',
      bestMonths: [6, 7, 8, 9],
      averageBudget: 360.00,
      popularityScore: 81,
      latitude: -2.743300,
      longitude: -42.826700,
      timezone: 'America/Fortaleza',
      categoryNames: ['Natureza', 'Aventura', 'Família'],
    },

    // América do Sul
    {
      name: 'Buenos Aires',
      city: 'Buenos Aires',
      country: 'Argentina',
      countryCode: 'AR',
      description: 'A Paris da América do Sul encanta com seus bairros charmosos, tango, arquitetura europeia e gastronomia excepcional. San Telmo, Palermo e La Boca são imperdíveis.',
      shortDescription: 'Tango, gastronomia e arquitetura europeia',
      bestMonths: [3, 4, 5, 9, 10, 11],
      averageBudget: 450.00,
      popularityScore: 95,
      latitude: -34.603722,
      longitude: -58.381592,
      timezone: 'America/Argentina/Buenos_Aires',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico', 'Romance'],
    },
    {
      name: 'Santiago',
      city: 'Santiago',
      country: 'Chile',
      countryCode: 'CL',
      description: 'Capital do Chile, aos pés da Cordilheira dos Andes. Oferece excelente gastronomia, vinícolas renomadas nos arredores e fácil acesso a ski resorts e praias.',
      shortDescription: 'Cordilheira dos Andes e vinícolas premiadas',
      bestMonths: [3, 4, 5, 9, 10, 11],
      averageBudget: 420.00,
      popularityScore: 93,
      latitude: -33.448890,
      longitude: -70.669265,
      timezone: 'America/Santiago',
      categoryNames: ['Metrópole', 'Gastronômico', 'Aventura'],
    },
    {
      name: 'Lima',
      city: 'Lima',
      country: 'Peru',
      countryCode: 'PE',
      description: 'Capital gastronômica da América do Sul, Lima combina história colonial com culinária de classe mundial. Porta de entrada para Machu Picchu.',
      shortDescription: 'Capital gastronômica e história milenar',
      bestMonths: [1, 2, 3, 11, 12],
      averageBudget: 380.00,
      popularityScore: 87,
      latitude: -12.046374,
      longitude: -77.042793,
      timezone: 'America/Lima',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico', 'Cidade Histórica'],
    },
    {
      name: 'Cusco e Machu Picchu',
      city: 'Cusco',
      country: 'Peru',
      countryCode: 'PE',
      description: 'Antiga capital do Império Inca, Cusco é a porta de entrada para Machu Picchu, uma das Sete Maravilhas do Mundo Moderno. Oferece história milenar e paisagens deslumbrantes.',
      shortDescription: 'Machu Picchu e legado Inca',
      bestMonths: [4, 5, 6, 7, 8, 9, 10],
      averageBudget: 500.00,
      popularityScore: 92,
      latitude: -13.531950,
      longitude: -71.967463,
      timezone: 'America/Lima',
      categoryNames: ['Montanha', 'Cidade Histórica', 'Cultural', 'Aventura'],
    },
    {
      name: 'Montevidéu',
      city: 'Montevidéu',
      country: 'Uruguay',
      countryCode: 'UY',
      description: 'Capital tranquila do Uruguai, oferece arquitetura colonial, praias urbanas, mercados tradicionais e a famosa Ciudad Vieja. Próxima a Punta del Este.',
      shortDescription: 'Charme colonial e praias tranquilas',
      bestMonths: [1, 2, 3, 11, 12],
      averageBudget: 360.00,
      popularityScore: 75,
      latitude: -34.901112,
      longitude: -56.164532,
      timezone: 'America/Montevideo',
      categoryNames: ['Metrópole', 'Cidade Histórica', 'Praia'],
    },
    {
      name: 'Cartagena',
      city: 'Cartagena',
      country: 'Colombia',
      countryCode: 'CO',
      description: 'Cidade murada no Caribe colombiano, com arquitetura colonial preservada, praias paradisíacas e vida noturna vibrante. Patrimônio Mundial da UNESCO.',
      shortDescription: 'Cidade murada e Caribe colombiano',
      bestMonths: [1, 2, 3, 12],
      averageBudget: 400.00,
      popularityScore: 81,
      latitude: 10.391049,
      longitude: -75.479426,
      timezone: 'America/Bogota',
      categoryNames: ['Praia', 'Cidade Histórica', 'Cultural', 'Romance'],
    },

    // América do Norte
    {
      name: 'Miami',
      city: 'Miami',
      country: 'United States',
      countryCode: 'US',
      description: 'Cidade cosmopolita da Flórida, famosa por suas praias, vida noturna, compras e arquitetura Art Déco em South Beach. Porta de entrada para cruzeiros no Caribe.',
      shortDescription: 'Praias, compras e vida noturna em South Beach',
      bestMonths: [1, 2, 3, 4, 11, 12],
      averageBudget: 800.00,
      popularityScore: 94,
      latitude: 25.761680,
      longitude: -80.191790,
      timezone: 'America/New_York',
      categoryNames: ['Praia', 'Metrópole', 'Compras', 'Luxo'],
    },
    {
      name: 'Orlando',
      city: 'Orlando',
      country: 'United States',
      countryCode: 'US',
      description: 'Capital mundial dos parques temáticos, abriga Walt Disney World, Universal Studios e SeaWorld. Destino perfeito para famílias.',
      shortDescription: 'Capital mundial dos parques temáticos',
      bestMonths: [1, 2, 3, 4, 5, 10, 11, 12],
      averageBudget: 900.00,
      popularityScore: 91,
      latitude: 28.538336,
      longitude: -81.379234,
      timezone: 'America/New_York',
      categoryNames: ['Família', 'Aventura'],
    },
    {
      name: 'Nova York',
      city: 'New York',
      country: 'United States',
      countryCode: 'US',
      description: 'A cidade que nunca dorme oferece museus icônicos, Broadway, arranha-céus, compras na 5ª Avenida, Central Park e uma diversidade cultural incomparável.',
      shortDescription: 'Broadway, arranha-céus e diversidade cultural',
      bestMonths: [4, 5, 6, 9, 10],
      averageBudget: 1200.00,
      popularityScore: 98,
      latitude: 40.712776,
      longitude: -74.005974,
      timezone: 'America/New_York',
      categoryNames: ['Metrópole', 'Cultural', 'Compras', 'Luxo'],
    },
    {
      name: 'São Francisco',
      city: 'San Francisco',
      country: 'United States',
      countryCode: 'US',
      description: 'São Francisco encanta com a Golden Gate Bridge, bairros icônicos como Fisherman\'s Wharf e Mission District, tecnologia no Vale do Silício e gastronomia sofisticada.',
      shortDescription: 'Golden Gate, tecnologia e gastronomia californiana',
      bestMonths: [4, 5, 9, 10],
      averageBudget: 1100.00,
      popularityScore: 92,
      latitude: 37.774929,
      longitude: -122.419418,
      timezone: 'America/Los_Angeles',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico', 'Compras'],
    },
    {
      name: 'Los Angeles',
      city: 'Los Angeles',
      country: 'United States',
      countryCode: 'US',
      description: 'Capital mundial do cinema, com Hollywood, estúdios, praias como Santa Monica e Venice, e gastronomia multicultural. Combina glamour com cenários californianos icônicos.',
      shortDescription: 'Hollywood, Santa Monica e estilo californiano',
      bestMonths: [3, 4, 5, 9, 10],
      averageBudget: 950.00,
      popularityScore: 88,
      latitude: 34.052235,
      longitude: -118.243683,
      timezone: 'America/Los_Angeles',
      categoryNames: ['Metrópole', 'Praia', 'Gastronômico', 'Compras'],
    },
    {
      name: 'Cancún',
      city: 'Cancún',
      country: 'México',
      countryCode: 'MX',
      description: 'Destino mais famoso da Riviera Maya, com resorts all-inclusive, mar azul-turquesa, vida noturna vibrante e proximidade às ruínas maias de Tulum e Chichén Itzá.',
      shortDescription: 'Resorts caribenhos e ruínas maias na Riviera Maya',
      bestMonths: [1, 2, 3, 4, 11, 12],
      averageBudget: 780.00,
      popularityScore: 90,
      latitude: 21.161908,
      longitude: -86.851528,
      timezone: 'America/Cancun',
      categoryNames: ['Praia', 'Romance', 'Aventura', 'Luxo'],
    },
    {
      name: 'Vancouver',
      city: 'Vancouver',
      country: 'Canadá',
      countryCode: 'CA',
      description: 'Cidade costeira cercada por montanhas, parques urbanos como Stanley Park, esportes ao ar livre e uma cena gastronômica multicultural vibrante.',
      shortDescription: 'Paisagens entre montanhas e mar no Canadá',
      bestMonths: [5, 6, 7, 8, 9],
      averageBudget: 1000.00,
      popularityScore: 85,
      latitude: 49.282729,
      longitude: -123.120738,
      timezone: 'America/Vancouver',
      categoryNames: ['Natureza', 'Metrópole', 'Aventura'],
    },

    // Europa
    {
      name: 'Lisboa',
      city: 'Lisboa',
      country: 'Portugal',
      countryCode: 'PT',
      description: 'Capital portuguesa encanta com seus azulejos, bondes históricos, fado, pastéis de Belém e vistas panorâmicas. Clima ameno e custo acessível para a Europa.',
      shortDescription: 'Azulejos, fado e gastronomia portuguesa',
      bestMonths: [4, 5, 6, 9, 10],
      averageBudget: 600.00,
      popularityScore: 89,
      latitude: 38.722252,
      longitude: -9.139337,
      timezone: 'Europe/Lisbon',
      categoryNames: ['Metrópole', 'Cidade Histórica', 'Cultural', 'Gastronômico'],
    },
    {
      name: 'Paris',
      city: 'Paris',
      country: 'France',
      countryCode: 'FR',
      description: 'A Cidade Luz é sinônimo de romance, arte e gastronomia. Torre Eiffel, Louvre, Champs-Élysées e cafés charmosos fazem de Paris um destino atemporal.',
      shortDescription: 'Cidade do romance, arte e gastronomia',
      bestMonths: [4, 5, 6, 9, 10],
      averageBudget: 1000.00,
      popularityScore: 97,
      latitude: 48.856613,
      longitude: 2.352222,
      timezone: 'Europe/Paris',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico', 'Romance', 'Luxo'],
    },
    {
      name: 'Roma',
      city: 'Rome',
      country: 'Italy',
      countryCode: 'IT',
      description: 'A Cidade Eterna abriga o Coliseu, Vaticano, Fontana di Trevi e ruínas milenares. Combina história antiga com gastronomia italiana autêntica.',
      shortDescription: 'Coliseu, Vaticano e história milenar',
      bestMonths: [4, 5, 6, 9, 10],
      averageBudget: 850.00,
      popularityScore: 88,
      latitude: 41.902782,
      longitude: 12.496366,
      timezone: 'Europe/Rome',
      categoryNames: ['Metrópole', 'Cidade Histórica', 'Cultural', 'Gastronômico'],
    },
    {
      name: 'Barcelona',
      city: 'Barcelona',
      country: 'Spain',
      countryCode: 'ES',
      description: 'Capital catalã combina praias urbanas, arquitetura de Gaudí (Sagrada Família), gastronomia excepcional e vida noturna vibrante.',
      shortDescription: 'Gaudí, praias e gastronomia catalã',
      bestMonths: [5, 6, 9, 10],
      averageBudget: 750.00,
      popularityScore: 87,
      latitude: 41.385064,
      longitude: 2.173404,
      timezone: 'Europe/Madrid',
      categoryNames: ['Metrópole', 'Praia', 'Cultural', 'Gastronômico'],
    },
    {
      name: 'Madrid',
      city: 'Madrid',
      country: 'Spain',
      countryCode: 'ES',
      description: 'Capital espanhola oferece museus de classe mundial (Prado, Reina Sofía), parques encantadores, tapas deliciosas e vida noturna agitada.',
      shortDescription: 'Museus de arte e tapas espanholas',
      bestMonths: [4, 5, 6, 9, 10],
      averageBudget: 700.00,
      popularityScore: 86,
      latitude: 40.416775,
      longitude: -3.703790,
      timezone: 'Europe/Madrid',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico'],
    },

    // Ásia
    {
      name: 'Tóquio',
      city: 'Tóquio',
      country: 'Japão',
      countryCode: 'JP',
      description: 'Metrópole futurista que mescla tecnologia, cultura pop e tradição. Shibuya e Shinjuku vibram com neon, enquanto templos históricos e mercados gastronômicos encantam.',
      shortDescription: 'Tecnologia, tradição e gastronomia japonesa',
      bestMonths: [3, 4, 5, 10, 11],
      averageBudget: 1300.00,
      popularityScore: 96,
      latitude: 35.689487,
      longitude: 139.691711,
      timezone: 'Asia/Tokyo',
      categoryNames: ['Metrópole', 'Cultural', 'Gastronômico', 'Compras'],
    },
    {
      name: 'Dubai',
      city: 'Dubai',
      country: 'Emirados Árabes Unidos',
      countryCode: 'AE',
      description: 'Cidade futurista no deserto com arranha-céus icônicos como o Burj Khalifa, shoppings gigantescos, safáris no deserto e hotéis de luxo incomparáveis.',
      shortDescription: 'Arranha-céus, deserto e experiências de luxo',
      bestMonths: [11, 12, 1, 2, 3, 4],
      averageBudget: 1400.00,
      popularityScore: 90,
      latitude: 25.204849,
      longitude: 55.270782,
      timezone: 'Asia/Dubai',
      categoryNames: ['Metrópole', 'Luxo', 'Compras', 'Aventura'],
    },
    {
      name: 'Bali (Seminyak e Ubud)',
      city: 'Denpasar',
      country: 'Indonésia',
      countryCode: 'ID',
      description: 'Ilha dos deuses com templos hindus, praias ensolaradas, spas renomados, campos de arroz em Ubud e beach clubs sofisticados em Seminyak.',
      shortDescription: 'Templos, praias e bem-estar balinês',
      bestMonths: [4, 5, 6, 7, 8, 9],
      averageBudget: 680.00,
      popularityScore: 88,
      latitude: -8.409518,
      longitude: 115.188919,
      timezone: 'Asia/Makassar',
      categoryNames: ['Praia', 'Natureza', 'Romance', 'Luxo'],
    },

    // África
    {
      name: 'Cidade do Cabo',
      city: 'Cidade do Cabo',
      country: 'África do Sul',
      countryCode: 'ZA',
      description: 'Cidade costeira com a icônica Table Mountain, vinícolas em Stellenbosch, praias como Camps Bay e rica cena cultural e gastronômica.',
      shortDescription: 'Table Mountain, vinhos e praias sul-africanas',
      bestMonths: [11, 12, 1, 2, 3],
      averageBudget: 950.00,
      popularityScore: 84,
      latitude: -33.924869,
      longitude: 18.424055,
      timezone: 'Africa/Johannesburg',
      categoryNames: ['Natureza', 'Aventura', 'Praia', 'Gastronômico'],
    },
    {
      name: 'Marrakesh',
      city: 'Marrakesh',
      country: 'Marrocos',
      countryCode: 'MA',
      description: 'Cidade imperial marroquina com souks coloridos, palácios ornamentados, riads charmosos e excursões ao deserto do Saara.',
      shortDescription: 'Souks perfumados e riads tradicionais',
      bestMonths: [3, 4, 5, 9, 10],
      averageBudget: 680.00,
      popularityScore: 80,
      latitude: 31.629472,
      longitude: -7.981084,
      timezone: 'Africa/Casablanca',
      categoryNames: ['Cultural', 'Gastronômico', 'Compras', 'Aventura'],
    },

    // Oceania
    {
      name: 'Sydney',
      city: 'Sydney',
      country: 'Austrália',
      countryCode: 'AU',
      description: 'Metrópole australiana com ícones como a Opera House e Harbour Bridge, praias famosas como Bondi e parques nacionais acessíveis.',
      shortDescription: 'Opera House, Harbour Bridge e lifestyle australiano',
      bestMonths: [9, 10, 11, 12, 1, 2],
      averageBudget: 1250.00,
      popularityScore: 89,
      latitude: -33.868820,
      longitude: 151.209290,
      timezone: 'Australia/Sydney',
      categoryNames: ['Metrópole', 'Praia', 'Natureza'],
    },
    {
      name: 'Queenstown',
      city: 'Queenstown',
      country: 'Nova Zelândia',
      countryCode: 'NZ',
      description: 'Capital da aventura da Nova Zelândia com esportes radicais, trilhas alpinas, vinhos de Central Otago e cenários do lago Wakatipu.',
      shortDescription: 'Aventura alpina às margens do lago Wakatipu',
      bestMonths: [1, 2, 3, 7, 8, 9],
      averageBudget: 980.00,
      popularityScore: 82,
      latitude: -45.031162,
      longitude: 168.662643,
      timezone: 'Pacific/Auckland',
      categoryNames: ['Aventura', 'Natureza', 'Família'],
    },

    // Caribe
    {
      name: 'Punta Cana',
      city: 'Punta Cana',
      country: 'Dominican Republic',
      countryCode: 'DO',
      description: 'Paraíso caribenho com resorts all-inclusive, praias de areia branca, águas cristalinas e atividades aquáticas. Ideal para lua de mel e famílias.',
      shortDescription: 'Resorts all-inclusive e praias caribenhas',
      bestMonths: [1, 2, 3, 4, 11, 12],
      averageBudget: 700.00,
      popularityScore: 83,
      latitude: 18.581812,
      longitude: -68.404502,
      timezone: 'America/Santo_Domingo',
      categoryNames: ['Praia', 'Romance', 'Família', 'Luxo'],
    },
    {
      name: 'Curaçao',
      city: 'Willemstad',
      country: 'Curaçao',
      countryCode: 'CW',
      description: 'Ilha caribenha holandesa com arquitetura colorida, praias paradisíacas, mergulho de classe mundial e cultura multicultural única.',
      shortDescription: 'Arquitetura colorida e mergulho caribenho',
      bestMonths: [1, 2, 3, 4, 5, 12],
      averageBudget: 650.00,
      popularityScore: 78,
      latitude: 12.122422,
      longitude: -68.882423,
      timezone: 'America/Curacao',
      categoryNames: ['Praia', 'Aventura', 'Cultural'],
    },
  ];

  for (const dest of destinations) {
    const { categoryNames, ...destData } = dest;
    const media = destinationMedia[destData.name];
    const destinationInput = {
      ...destData,
      heroImageUrl: media?.heroImageUrl ?? null,
      galleryImageUrls: media?.galleryImageUrls ?? [],
    };

    // Check if destination already exists
    const existing = await prisma.destination.findFirst({
      where: {
        name: destData.name,
        city: destData.city,
        country: destData.country
      }
    });

    const destination = existing
      ? await prisma.destination.update({
          where: { id: existing.id },
          data: destinationInput
        })
      : await prisma.destination.create({
          data: destinationInput
        });

    // Link categories
    for (const categoryName of categoryNames) {
      const category = await prisma.category.findFirst({
        where: { name: categoryName }
      });

      if (category) {
        await prisma.destinationCategory.upsert({
          where: {
            destinationId_categoryId: {
              destinationId: destination.id,
              categoryId: category.id
            }
          },
          update: {},
          create: {
            destinationId: destination.id,
            categoryId: category.id
          }
        });
      }
    }
  }

  console.log(`✅ Created ${destinations.length} destinations`);
}
