import { PrismaClient } from '../../src/generated/prisma';

export async function seedHotels(prisma: PrismaClient) {
  console.log('🏨 Seeding hotels...');

  const hotels = [
    // São Paulo
    {
      hotelId: 'hotel-sp-001',
      name: 'Hotel Unique',
      city: 'São Paulo',
      address: 'Av. Brigadeiro Luís Antônio, 4700 - Jardim Paulista',
      latitude: -23.571944,
      longitude: -46.672222,
      distanceToCenter: 3.5,
      distanceToAirport: 25.0,
      rating: 4.7,
      reviewCount: 1823,
      nightlyRate: 850.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'spa', 'restaurante_premiado', 'wifi', 'estacionamento'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-sp-002',
      name: 'Ibis Paulista',
      city: 'São Paulo',
      address: 'Av. Paulista, 2355 - Bela Vista',
      latitude: -23.558611,
      longitude: -46.661944,
      distanceToCenter: 2.0,
      distanceToAirport: 27.0,
      rating: 4.2,
      reviewCount: 3421,
      nightlyRate: 280.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['wifi', 'localizacao_central', 'estacionamento'],
      categoryNames: ['Hotel Econômico', 'Centro'],
    },

    // Rio de Janeiro
    {
      hotelId: 'hotel-rj-001',
      name: 'Copacabana Palace',
      city: 'Rio de Janeiro',
      address: 'Av. Atlântica, 1702 - Copacabana',
      latitude: -22.968611,
      longitude: -43.180000,
      distanceToCenter: 8.0,
      distanceToAirport: 25.0,
      rating: 4.9,
      reviewCount: 2145,
      nightlyRate: 1800.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'spa', 'praia', 'restaurante_premiado', 'luxo', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Praia'],
    },
    {
      hotelId: 'hotel-rj-002',
      name: 'Ibis Copacabana',
      city: 'Rio de Janeiro',
      address: 'Rua Figueiredo de Magalhães, 875 - Copacabana',
      latitude: -22.968889,
      longitude: -43.187778,
      distanceToCenter: 8.5,
      distanceToAirport: 26.0,
      rating: 4.1,
      reviewCount: 2892,
      nightlyRate: 320.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['wifi', 'praia', 'estacionamento'],
      categoryNames: ['Hotel Econômico', 'Praia'],
    },

    // Salvador
    {
      hotelId: 'hotel-ssa-001',
      name: 'Hotel Fasano Salvador',
      city: 'Salvador',
      address: 'Praça Castro Alves - Centro',
      latitude: -12.977222,
      longitude: -38.510556,
      distanceToCenter: 0.5,
      distanceToAirport: 25.0,
      rating: 4.8,
      reviewCount: 892,
      nightlyRate: 1200.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'spa', 'restaurante_premiado', 'vista_mar', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-ssa-002',
      name: 'Wish Hotel da Bahia',
      city: 'Salvador',
      address: 'Av. Sete de Setembro, 1537 - Vitória',
      latitude: -12.990000,
      longitude: -38.505000,
      distanceToCenter: 2.0,
      distanceToAirport: 23.0,
      rating: 4.3,
      reviewCount: 1523,
      nightlyRate: 380.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'wifi', 'vista_mar'],
      categoryNames: ['Hotel Boutique', 'Centro'],
    },

    // Recife / Porto de Galinhas
    {
      hotelId: 'hotel-rec-001',
      name: 'Nannai Resort & Spa',
      city: 'Recife',
      address: 'Rodovia PE-09, s/n - Porto de Galinhas',
      latitude: -8.500000,
      longitude: -35.006944,
      distanceToCenter: 65.0,
      distanceToAirport: 55.0,
      rating: 4.8,
      reviewCount: 1675,
      nightlyRate: 1400.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: false,
      highlights: ['resort', 'spa', 'piscina', 'praia', 'all_inclusive', 'wifi'],
      categoryNames: ['Resort', 'Praia', 'Hotel de Luxo'],
    },
    {
      hotelId: 'hotel-rec-002',
      name: 'Pousada Tabapitanga',
      city: 'Recife',
      address: 'Loteamento Merepe III - Porto de Galinhas',
      latitude: -8.503333,
      longitude: -35.009167,
      distanceToCenter: 66.0,
      distanceToAirport: 56.0,
      rating: 4.5,
      reviewCount: 2341,
      nightlyRate: 650.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'praia', 'wifi'],
      categoryNames: ['Pousada', 'Praia'],
    },

    // Buenos Aires
    {
      hotelId: 'hotel-bue-001',
      name: 'Alvear Palace Hotel',
      city: 'Buenos Aires',
      address: 'Av. Alvear 1891 - Recoleta',
      latitude: -34.593889,
      longitude: -58.388611,
      distanceToCenter: 2.5,
      distanceToAirport: 32.0,
      rating: 4.9,
      reviewCount: 1432,
      nightlyRate: 2200.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['luxo', 'spa', 'piscina', 'restaurante_premiado', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-bue-002',
      name: 'NH Buenos Aires City',
      city: 'Buenos Aires',
      address: 'Bolívar 160 - San Telmo',
      latitude: -34.617500,
      longitude: -58.373056,
      distanceToCenter: 1.5,
      distanceToAirport: 35.0,
      rating: 4.3,
      reviewCount: 2567,
      nightlyRate: 420.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['wifi', 'localizacao_central', 'estacionamento'],
      categoryNames: ['Hotel Econômico', 'Centro'],
    },

    // Santiago
    {
      hotelId: 'hotel-scl-001',
      name: 'The Ritz-Carlton Santiago',
      city: 'Santiago',
      address: 'El Alcalde 15 - Las Condes',
      latitude: -33.413056,
      longitude: -70.579444,
      distanceToCenter: 10.0,
      distanceToAirport: 20.0,
      rating: 4.8,
      reviewCount: 1234,
      nightlyRate: 1800.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['luxo', 'spa', 'piscina', 'vista_andes', 'restaurante_premiado', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-scl-002',
      name: 'Ibis Santiago Providencia',
      city: 'Santiago',
      address: 'Eliodoro Yáñez 1800 - Providencia',
      latitude: -33.434167,
      longitude: -70.605833,
      distanceToCenter: 5.0,
      distanceToAirport: 25.0,
      rating: 4.2,
      reviewCount: 1876,
      nightlyRate: 380.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['wifi', 'localizacao_central'],
      categoryNames: ['Hotel Econômico', 'Centro'],
    },

    // Lisboa
    {
      hotelId: 'hotel-lis-001',
      name: 'Four Seasons Hotel Ritz Lisbon',
      city: 'Lisboa',
      address: 'Rua Rodrigo da Fonseca, 88',
      latitude: 38.727500,
      longitude: -9.153889,
      distanceToCenter: 1.5,
      distanceToAirport: 8.0,
      rating: 4.8,
      reviewCount: 1623,
      nightlyRate: 2800.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['luxo', 'spa', 'piscina', 'restaurante_premiado', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-lis-002',
      name: 'My Story Hotel Rossio',
      city: 'Lisboa',
      address: 'Praça Dom Pedro IV, 59',
      latitude: 38.713889,
      longitude: -9.139444,
      distanceToCenter: 0.2,
      distanceToAirport: 7.5,
      rating: 4.4,
      reviewCount: 3421,
      nightlyRate: 550.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['wifi', 'localizacao_central', 'historico'],
      categoryNames: ['Hotel Boutique', 'Centro'],
    },

    // Paris
    {
      hotelId: 'hotel-par-001',
      name: 'Le Meurice',
      city: 'Paris',
      address: '228 Rue de Rivoli',
      latitude: 48.865000,
      longitude: 2.328889,
      distanceToCenter: 1.0,
      distanceToAirport: 25.0,
      rating: 4.9,
      reviewCount: 2134,
      nightlyRate: 4500.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['luxo', 'spa', 'restaurante_estrela_michelin', 'historico', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-par-002',
      name: 'Hotel Elysées Union',
      city: 'Paris',
      address: '44 Rue de l\'Amiral Hamelin',
      latitude: 48.869167,
      longitude: 2.290000,
      distanceToCenter: 3.5,
      distanceToAirport: 27.0,
      rating: 4.3,
      reviewCount: 1823,
      nightlyRate: 800.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['wifi', 'localizacao_central', 'charmoso'],
      categoryNames: ['Hotel Boutique', 'Centro'],
    },

    // Miami
    {
      hotelId: 'hotel-mia-001',
      name: 'Fontainebleau Miami Beach',
      city: 'Miami',
      address: '4441 Collins Avenue',
      latitude: 25.819722,
      longitude: -80.122500,
      distanceToCenter: 8.0,
      distanceToAirport: 15.0,
      rating: 4.7,
      reviewCount: 5234,
      nightlyRate: 3200.00,
      currency: 'BRL',
      breakfastIncluded: false,
      refundable: true,
      highlights: ['resort', 'piscina', 'praia', 'spa', 'restaurantes', 'wifi'],
      categoryNames: ['Resort', 'Praia', 'Hotel de Luxo'],
    },
    {
      hotelId: 'hotel-mia-002',
      name: 'Aloft Miami Brickell',
      city: 'Miami',
      address: '1395 Brickell Avenue',
      latitude: 25.761667,
      longitude: -80.191944,
      distanceToCenter: 2.0,
      distanceToAirport: 10.0,
      rating: 4.4,
      reviewCount: 2897,
      nightlyRate: 900.00,
      currency: 'BRL',
      breakfastIncluded: false,
      refundable: true,
      highlights: ['wifi', 'piscina', 'moderno'],
      categoryNames: ['Hotel Boutique', 'Centro'],
    },

    // Punta Cana
    {
      hotelId: 'hotel-puj-001',
      name: 'Excellence Punta Cana',
      city: 'Punta Cana',
      address: 'Playa Uvero Alto',
      latitude: 18.731944,
      longitude: -68.407500,
      distanceToCenter: 25.0,
      distanceToAirport: 40.0,
      rating: 4.8,
      reviewCount: 4567,
      nightlyRate: 2800.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: false,
      highlights: ['resort', 'all_inclusive', 'praia', 'spa', 'piscina', 'adultos_apenas', 'wifi'],
      categoryNames: ['Resort', 'Praia', 'Hotel de Luxo'],
    },
    {
      hotelId: 'hotel-puj-002',
      name: 'Hard Rock Hotel & Casino Punta Cana',
      city: 'Punta Cana',
      address: 'Boulevard Turístico del Este',
      latitude: 18.554167,
      longitude: -68.372778,
      distanceToCenter: 5.0,
      distanceToAirport: 18.0,
      rating: 4.6,
      reviewCount: 6234,
      nightlyRate: 2200.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: false,
      highlights: ['resort', 'all_inclusive', 'praia', 'casino', 'piscina', 'entretenimento', 'wifi'],
      categoryNames: ['Resort', 'Praia'],
    },
  ];

  for (const hotel of hotels) {
    const { categoryNames, ...hotelData } = hotel;

    const createdHotel = await prisma.hotel.upsert({
      where: { hotelId: hotelData.hotelId },
      update: hotelData,
      create: hotelData,
    });

    // Link categories
    for (const categoryName of categoryNames) {
      const category = await prisma.category.findFirst({
        where: { name: categoryName }
      });

      if (category) {
        await prisma.hotelCategory.upsert({
          where: {
            hotelId_categoryId: {
              hotelId: createdHotel.id,
              categoryId: category.id
            }
          },
          update: {},
          create: {
            hotelId: createdHotel.id,
            categoryId: category.id
          }
        });
      }
    }
  }

  console.log(`✅ Created ${hotels.length} hotels`);
}
