import { PrismaClient } from '../../src/generated/prisma';

export async function seedHotels(prisma: PrismaClient) {
  console.log('🏨 Seeding hotels...');

  const defaultHotelGallery = [
    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80',
  ];

  const hotelMedia: Record<string, { heroImageUrl: string; galleryImageUrls: string[] }> = {
    'hotel-sp-001': {
      heroImageUrl: 'https://images.unsplash.com/photo-1501117716987-c8e1ecb2100d?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-sp-002': {
      heroImageUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-rj-001': {
      heroImageUrl: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-rj-002': {
      heroImageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-ssa-001': {
      heroImageUrl: 'https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-ssa-002': {
      heroImageUrl: 'https://images.unsplash.com/photo-1505761671935-60b3a7427bad?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-rec-001': {
      heroImageUrl: 'https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-rec-002': {
      heroImageUrl: 'https://images.unsplash.com/photo-1501117703631-ecfbcaaa60f9?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-bue-001': {
      heroImageUrl: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-bue-002': {
      heroImageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-scl-001': {
      heroImageUrl: 'https://images.unsplash.com/photo-1488340406467-0e78c76ebc4c?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-scl-002': {
      heroImageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-lis-001': {
      heroImageUrl: 'https://images.unsplash.com/photo-1512914890250-353c97b0f553?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-lis-002': {
      heroImageUrl: 'https://images.unsplash.com/photo-1559087867-b494dd8bdfbf?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-par-001': {
      heroImageUrl: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-par-002': {
      heroImageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-mia-001': {
      heroImageUrl: 'https://images.unsplash.com/photo-1505765050516-f72dcac9c60c?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-mia-002': {
      heroImageUrl: 'https://images.unsplash.com/photo-1502980426475-b83966705988?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-puj-001': {
      heroImageUrl: 'https://images.unsplash.com/photo-1470246973918-29a93221c455?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-puj-002': {
      heroImageUrl: 'https://images.unsplash.com/photo-1496412705862-e0088f16f791?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-sfo-001': {
      heroImageUrl: 'https://images.unsplash.com/photo-1540202404-0d6f8f5f5ca7?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-sfo-002': {
      heroImageUrl: 'https://images.unsplash.com/photo-1519822472278-5f1ce7c188b6?auto=format&fit=crop&w=1200&q=80',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-gra-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?gramado,boutique+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-gra-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?gramado,resort',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-jer-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?jericoacoara,resort',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-jer-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?jericoacoara,pousada',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-fen-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?noronha,resort',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-fen-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?noronha,pousada',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-bon-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?bonito,resort',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-bon-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?bonito,hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-mao-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?amazon,lodge',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-mao-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?manaus,boutique',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-len-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?lencois,maranhenses,resort',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-len-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?barreirinhas,pousada',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-cun-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?cancun,resort',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-cun-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?cancun,hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-lax-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?los+angeles,luxury+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-lax-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?santa+monica,hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-yvr-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?vancouver,luxury+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-yvr-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?vancouver,boutique+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-tyo-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?tokyo,luxury+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-tyo-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?tokyo,boutique+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-dxb-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?dubai,luxury+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-dxb-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?dubai,city+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-dps-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?bali,resort',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-dps-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?seminyak,beach+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-cpt-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?cape+town,luxury+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-cpt-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?cape+town,waterfront+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-syd-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?sydney,luxury+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-syd-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?sydney,boutique+hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-zqn-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?queenstown,luxury+lodge',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-zqn-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?queenstown,hotel',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-rak-001': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?marrakech,luxury+riad',
      galleryImageUrls: [...defaultHotelGallery],
    },
    'hotel-rak-002': {
      heroImageUrl: 'https://source.unsplash.com/1200x800/?marrakech,riad',
      galleryImageUrls: [...defaultHotelGallery],
    },
  };

  const hotels = [
    // São Paulo
    {
      hotelId: 'hotel-sp-001',
      name: 'Hotel Unique',
      city: 'São Paulo',
      address: 'Av. Brigadeiro Luís Antônio, 4700 - Jardim Paulista',
      latitude: -23.571944,
      longitude: -46.672222,
      distanceToCenter: 3.5,
      distanceToAirport: 25.0,
      rating: 4.7,
      reviewCount: 1823,
      nightlyRate: 850.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'spa', 'restaurante_premiado', 'wifi', 'estacionamento'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-sp-002',
      name: 'Ibis Paulista',
      city: 'São Paulo',
      address: 'Av. Paulista, 2355 - Bela Vista',
      latitude: -23.558611,
      longitude: -46.661944,
      distanceToCenter: 2.0,
      distanceToAirport: 27.0,
      rating: 4.2,
      reviewCount: 3421,
      nightlyRate: 280.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['wifi', 'localizacao_central', 'estacionamento'],
      categoryNames: ['Hotel Econômico', 'Centro'],
    },

    // Rio de Janeiro
    {
      hotelId: 'hotel-rj-001',
      name: 'Copacabana Palace',
      city: 'Rio de Janeiro',
      address: 'Av. Atlântica, 1702 - Copacabana',
      latitude: -22.968611,
      longitude: -43.180000,
      distanceToCenter: 8.0,
      distanceToAirport: 25.0,
      rating: 4.9,
      reviewCount: 2145,
      nightlyRate: 1800.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'spa', 'praia', 'restaurante_premiado', 'luxo', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Praia'],
    },
    {
      hotelId: 'hotel-rj-002',
      name: 'Ibis Copacabana',
      city: 'Rio de Janeiro',
      address: 'Rua Figueiredo de Magalhães, 875 - Copacabana',
      latitude: -22.968889,
      longitude: -43.187778,
      distanceToCenter: 8.5,
      distanceToAirport: 26.0,
      rating: 4.1,
      reviewCount: 2892,
      nightlyRate: 320.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['wifi', 'praia', 'estacionamento'],
      categoryNames: ['Hotel Econômico', 'Praia'],
    },

    // Salvador
    {
      hotelId: 'hotel-ssa-001',
      name: 'Hotel Fasano Salvador',
      city: 'Salvador',
      address: 'Praça Castro Alves - Centro',
      latitude: -12.977222,
      longitude: -38.510556,
      distanceToCenter: 0.5,
      distanceToAirport: 25.0,
      rating: 4.8,
      reviewCount: 892,
      nightlyRate: 1200.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'spa', 'restaurante_premiado', 'vista_mar', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-ssa-002',
      name: 'Wish Hotel da Bahia',
      city: 'Salvador',
      address: 'Av. Sete de Setembro, 1537 - Vitória',
      latitude: -12.990000,
      longitude: -38.505000,
      distanceToCenter: 2.0,
      distanceToAirport: 23.0,
      rating: 4.3,
      reviewCount: 1523,
      nightlyRate: 380.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'wifi', 'vista_mar'],
      categoryNames: ['Hotel Boutique', 'Centro'],
    },

    // Recife / Porto de Galinhas
    {
      hotelId: 'hotel-rec-001',
      name: 'Nannai Resort & Spa',
      city: 'Recife',
      address: 'Rodovia PE-09, s/n - Porto de Galinhas',
      latitude: -8.500000,
      longitude: -35.006944,
      distanceToCenter: 65.0,
      distanceToAirport: 55.0,
      rating: 4.8,
      reviewCount: 1675,
      nightlyRate: 1400.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: false,
      highlights: ['resort', 'spa', 'piscina', 'praia', 'all_inclusive', 'wifi'],
      categoryNames: ['Resort', 'Praia', 'Hotel de Luxo'],
    },
    {
      hotelId: 'hotel-rec-002',
      name: 'Pousada Tabapitanga',
      city: 'Recife',
      address: 'Loteamento Merepe III - Porto de Galinhas',
      latitude: -8.503333,
      longitude: -35.009167,
      distanceToCenter: 66.0,
      distanceToAirport: 56.0,
      rating: 4.5,
      reviewCount: 2341,
      nightlyRate: 650.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'praia', 'wifi'],
      categoryNames: ['Pousada', 'Praia'],
    },

    // Buenos Aires
    {
      hotelId: 'hotel-bue-001',
      name: 'Alvear Palace Hotel',
      city: 'Buenos Aires',
      address: 'Av. Alvear 1891 - Recoleta',
      latitude: -34.593889,
      longitude: -58.388611,
      distanceToCenter: 2.5,
      distanceToAirport: 32.0,
      rating: 4.9,
      reviewCount: 1432,
      nightlyRate: 2200.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['luxo', 'spa', 'piscina', 'restaurante_premiado', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-bue-002',
      name: 'NH Buenos Aires City',
      city: 'Buenos Aires',
      address: 'Bolívar 160 - San Telmo',
      latitude: -34.617500,
      longitude: -58.373056,
      distanceToCenter: 1.5,
      distanceToAirport: 35.0,
      rating: 4.3,
      reviewCount: 2567,
      nightlyRate: 420.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['wifi', 'localizacao_central', 'estacionamento'],
      categoryNames: ['Hotel Econômico', 'Centro'],
    },

    // Santiago
    {
      hotelId: 'hotel-scl-001',
      name: 'The Ritz-Carlton Santiago',
      city: 'Santiago',
      address: 'El Alcalde 15 - Las Condes',
      latitude: -33.413056,
      longitude: -70.579444,
      distanceToCenter: 10.0,
      distanceToAirport: 20.0,
      rating: 4.8,
      reviewCount: 1234,
      nightlyRate: 1800.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['luxo', 'spa', 'piscina', 'vista_andes', 'restaurante_premiado', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-scl-002',
      name: 'Ibis Santiago Providencia',
      city: 'Santiago',
      address: 'Eliodoro Yáñez 1800 - Providencia',
      latitude: -33.434167,
      longitude: -70.605833,
      distanceToCenter: 5.0,
      distanceToAirport: 25.0,
      rating: 4.2,
      reviewCount: 1876,
      nightlyRate: 380.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['wifi', 'localizacao_central'],
      categoryNames: ['Hotel Econômico', 'Centro'],
    },

    // Lisboa
    {
      hotelId: 'hotel-lis-001',
      name: 'Four Seasons Hotel Ritz Lisbon',
      city: 'Lisboa',
      address: 'Rua Rodrigo da Fonseca, 88',
      latitude: 38.727500,
      longitude: -9.153889,
      distanceToCenter: 1.5,
      distanceToAirport: 8.0,
      rating: 4.8,
      reviewCount: 1623,
      nightlyRate: 2800.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['luxo', 'spa', 'piscina', 'restaurante_premiado', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-lis-002',
      name: 'My Story Hotel Rossio',
      city: 'Lisboa',
      address: 'Praça Dom Pedro IV, 59',
      latitude: 38.713889,
      longitude: -9.139444,
      distanceToCenter: 0.2,
      distanceToAirport: 7.5,
      rating: 4.4,
      reviewCount: 3421,
      nightlyRate: 550.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['wifi', 'localizacao_central', 'historico'],
      categoryNames: ['Hotel Boutique', 'Centro'],
    },

    // Paris
    {
      hotelId: 'hotel-par-001',
      name: 'Le Meurice',
      city: 'Paris',
      address: '228 Rue de Rivoli',
      latitude: 48.865000,
      longitude: 2.328889,
      distanceToCenter: 1.0,
      distanceToAirport: 25.0,
      rating: 4.9,
      reviewCount: 2134,
      nightlyRate: 4500.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['luxo', 'spa', 'restaurante_estrela_michelin', 'historico', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-par-002',
      name: 'Hotel Elysées Union',
      city: 'Paris',
      address: '44 Rue de l\'Amiral Hamelin',
      latitude: 48.869167,
      longitude: 2.290000,
      distanceToCenter: 3.5,
      distanceToAirport: 27.0,
      rating: 4.3,
      reviewCount: 1823,
      nightlyRate: 800.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['wifi', 'localizacao_central', 'charmoso'],
      categoryNames: ['Hotel Boutique', 'Centro'],
    },

    // Miami
    {
      hotelId: 'hotel-mia-001',
      name: 'Fontainebleau Miami Beach',
      city: 'Miami',
      address: '4441 Collins Avenue',
      latitude: 25.819722,
      longitude: -80.122500,
      distanceToCenter: 8.0,
      distanceToAirport: 15.0,
      rating: 4.7,
      reviewCount: 5234,
      nightlyRate: 3200.00,
      currency: 'BRL',
      breakfastIncluded: false,
      refundable: true,
      highlights: ['resort', 'piscina', 'praia', 'spa', 'restaurantes', 'wifi'],
      categoryNames: ['Resort', 'Praia', 'Hotel de Luxo'],
    },
    {
      hotelId: 'hotel-mia-002',
      name: 'Aloft Miami Brickell',
      city: 'Miami',
      address: '1395 Brickell Avenue',
      latitude: 25.761667,
      longitude: -80.191944,
      distanceToCenter: 2.0,
      distanceToAirport: 10.0,
      rating: 4.4,
      reviewCount: 2897,
      nightlyRate: 900.00,
      currency: 'BRL',
      breakfastIncluded: false,
      refundable: true,
      highlights: ['wifi', 'piscina', 'moderno'],
      categoryNames: ['Hotel Boutique', 'Centro'],
    },

    // Punta Cana
    {
      hotelId: 'hotel-puj-001',
      name: 'Excellence Punta Cana',
      city: 'Punta Cana',
      address: 'Playa Uvero Alto',
      latitude: 18.731944,
      longitude: -68.407500,
      distanceToCenter: 25.0,
      distanceToAirport: 40.0,
      rating: 4.8,
      reviewCount: 4567,
      nightlyRate: 2800.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: false,
      highlights: ['resort', 'all_inclusive', 'praia', 'spa', 'piscina', 'adultos_apenas', 'wifi'],
      categoryNames: ['Resort', 'Praia', 'Hotel de Luxo'],
    },
    {
      hotelId: 'hotel-puj-002',
      name: 'Hard Rock Hotel & Casino Punta Cana',
      city: 'Punta Cana',
      address: 'Boulevard Turístico del Este',
      latitude: 18.554167,
      longitude: -68.372778,
      distanceToCenter: 5.0,
      distanceToAirport: 18.0,
      rating: 4.6,
      reviewCount: 6234,
      nightlyRate: 2200.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: false,
      highlights: ['resort', 'all_inclusive', 'praia', 'casino', 'piscina', 'entretenimento', 'wifi'],
      categoryNames: ['Resort', 'Praia'],
    },

    // San Francisco
    {
      hotelId: 'hotel-sfo-001',
      name: 'Fairmont San Francisco',
      city: 'San Francisco',
      address: '950 Mason St, San Francisco, CA',
      latitude: 37.792400,
      longitude: -122.410100,
      distanceToCenter: 0.5,
      distanceToAirport: 22.0,
      rating: 4.7,
      reviewCount: 3456,
      nightlyRate: 1850.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['luxo', 'vista_baia', 'spa', 'restaurante_premiado', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Centro'],
    },
    {
      hotelId: 'hotel-sfo-002',
      name: 'Hotel Zephyr Fisherman\'s Wharf',
      city: 'San Francisco',
      address: '250 Beach St, San Francisco, CA',
      latitude: 37.808000,
      longitude: -122.415900,
      distanceToCenter: 2.2,
      distanceToAirport: 24.0,
      rating: 4.3,
      reviewCount: 2890,
      nightlyRate: 980.00,
      currency: 'BRL',
      breakfastIncluded: false,
      refundable: true,
      highlights: ['vista_baia', 'wifi', 'area_externa', 'decor_moderno'],
      categoryNames: ['Hotel Boutique', 'Praia'],
    },

    // Gramado
    {
      hotelId: 'hotel-gra-001',
      name: 'Hotel Casa da Montanha',
      city: 'Gramado',
      address: 'Av. Borges de Medeiros, 3166 - Centro',
      latitude: -29.380345,
      longitude: -50.873913,
      distanceToCenter: 0.2,
      distanceToAirport: 115.0,
      rating: 4.8,
      reviewCount: 2187,
      nightlyRate: 980.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'spa', 'lareira', 'gastronomia', 'wifi'],
      categoryNames: ['Hotel Boutique', 'Hotel de Luxo'],
    },
    {
      hotelId: 'hotel-gra-002',
      name: 'Wish Serrano Resort & Convention',
      city: 'Gramado',
      address: 'Av. das Hortênsias, 1480 - Centro',
      latitude: -29.383263,
      longitude: -50.871920,
      distanceToCenter: 0.4,
      distanceToAirport: 110.0,
      rating: 4.5,
      reviewCount: 3120,
      nightlyRate: 560.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'spa', 'area_kids', 'wifi', 'gastronomia'],
      categoryNames: ['Resort', 'Hotel no Centro'],
    },

    // Jericoacoara
    {
      hotelId: 'hotel-jer-001',
      name: 'Essenza Hotel',
      city: 'Jijoca de Jericoacoara',
      address: 'Av. Beira Mar, s/n - Vila de Jericoacoara',
      latitude: -2.795431,
      longitude: -40.512846,
      distanceToCenter: 0.1,
      distanceToAirport: 32.0,
      rating: 4.7,
      reviewCount: 1890,
      nightlyRate: 1500.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'beira_mar', 'spa', 'adultos_apenas', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Hotel à Beira-Mar'],
    },
    {
      hotelId: 'hotel-jer-002',
      name: 'My Blue Hotel',
      city: 'Jijoca de Jericoacoara',
      address: 'Rua do Forró, s/n - Centro',
      latitude: -2.794652,
      longitude: -40.512145,
      distanceToCenter: 0.2,
      distanceToAirport: 32.0,
      rating: 4.3,
      reviewCount: 2540,
      nightlyRate: 680.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'praia', 'cafe_da_manha', 'wifi'],
      categoryNames: ['Pousada', 'Hotel à Beira-Mar'],
    },

    // Fernando de Noronha
    {
      hotelId: 'hotel-fen-001',
      name: 'Pousada Maravilha',
      city: 'Fernando de Noronha',
      address: 'BR-363, Sueste - Fernando de Noronha',
      latitude: -3.857122,
      longitude: -32.435116,
      distanceToCenter: 4.0,
      distanceToAirport: 3.5,
      rating: 4.9,
      reviewCount: 980,
      nightlyRate: 3200.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: false,
      highlights: ['vista_mar', 'piscina', 'spa', 'gastronomia', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Hotel à Beira-Mar'],
    },
    {
      hotelId: 'hotel-fen-002',
      name: 'Dolphin Hotel',
      city: 'Fernando de Noronha',
      address: 'Alameda do Boldró, s/n - Boldró',
      latitude: -3.855500,
      longitude: -32.433200,
      distanceToCenter: 3.0,
      distanceToAirport: 2.5,
      rating: 4.6,
      reviewCount: 1450,
      nightlyRate: 1450.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'wifi', 'transfer', 'experiencias'],
      categoryNames: ['Hotel Boutique', 'Pousada'],
    },

    // Bonito
    {
      hotelId: 'hotel-bon-001',
      name: 'Zagaia Eco Resort',
      city: 'Bonito',
      address: 'Rodovia Bonito-Três Morros, km 0',
      latitude: -21.132349,
      longitude: -56.485280,
      distanceToCenter: 4.0,
      distanceToAirport: 15.0,
      rating: 4.7,
      reviewCount: 2380,
      nightlyRate: 890.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'natureza', 'spa', 'passeios', 'wifi'],
      categoryNames: ['Resort', 'Spa'],
    },
    {
      hotelId: 'hotel-bon-002',
      name: 'Hotel Pirá Miúna',
      city: 'Bonito',
      address: 'Rua Coronel Pilad Rebuá, 1807 - Centro',
      latitude: -21.126951,
      longitude: -56.484269,
      distanceToCenter: 0.2,
      distanceToAirport: 14.0,
      rating: 4.4,
      reviewCount: 1180,
      nightlyRate: 430.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'cafe_da_manha', 'wifi', 'estacionamento'],
      categoryNames: ['Hotel Econômico', 'Hotel no Centro'],
    },

    // Manaus e Amazônia
    {
      hotelId: 'hotel-mao-001',
      name: 'Juma Amazon Lodge',
      city: 'Autazes',
      address: 'Rio Juma, Reserva do Juma',
      latitude: -3.254700,
      longitude: -59.907900,
      distanceToCenter: 95.0,
      distanceToAirport: 105.0,
      rating: 4.8,
      reviewCount: 760,
      nightlyRate: 1380.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: false,
      highlights: ['experiencia_selva', 'passeios', 'pensao_completa', 'guia_local', 'wifi'],
      categoryNames: ['Resort', 'Hotel Boutique'],
    },
    {
      hotelId: 'hotel-mao-002',
      name: 'Hotel Villa Amazônia',
      city: 'Manaus',
      address: 'Rua Dez de Julho, 315 - Centro',
      latitude: -3.131922,
      longitude: -60.023258,
      distanceToCenter: 0.3,
      distanceToAirport: 13.0,
      rating: 4.7,
      reviewCount: 1020,
      nightlyRate: 780.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'gastronomia', 'wifi', 'design'],
      categoryNames: ['Hotel Boutique', 'Hotel no Centro'],
    },

    // Lençóis Maranhenses
    {
      hotelId: 'hotel-len-001',
      name: 'Porto Preguiças Resort',
      city: 'Barreirinhas',
      address: 'Estrada do Carnaubal, s/n',
      latitude: -2.748500,
      longitude: -42.822900,
      distanceToCenter: 2.5,
      distanceToAirport: 260.0,
      rating: 4.5,
      reviewCount: 860,
      nightlyRate: 920.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'natureza', 'passeios', 'wifi'],
      categoryNames: ['Resort', 'Hotel Boutique'],
    },
    {
      hotelId: 'hotel-len-002',
      name: 'Encantes do Nordeste',
      city: 'Barreirinhas',
      address: 'Povoado Boa Vista, s/n',
      latitude: -2.742500,
      longitude: -42.830100,
      distanceToCenter: 4.0,
      distanceToAirport: 262.0,
      rating: 4.4,
      reviewCount: 540,
      nightlyRate: 420.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'chales', 'wifi', 'contato_natureza'],
      categoryNames: ['Pousada', 'Hotel Boutique'],
    },

    // Cancún
    {
      hotelId: 'hotel-cun-001',
      name: 'Moon Palace Cancun',
      city: 'Cancún',
      address: 'Carretera Cancun-Chetumal Km 340, Cancún',
      latitude: 21.079140,
      longitude: -86.845172,
      distanceToCenter: 25.0,
      distanceToAirport: 7.0,
      rating: 4.6,
      reviewCount: 8120,
      nightlyRate: 2100.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: false,
      highlights: ['all_inclusive', 'praia', 'piscina', 'spa', 'wifi'],
      categoryNames: ['Resort', 'Hotel de Luxo'],
    },
    {
      hotelId: 'hotel-cun-002',
      name: 'Selina Cancun Laguna Hotel Zone',
      city: 'Cancún',
      address: 'Blvd. Kukulcan Km 9, Zona Hotelera',
      latitude: 21.135324,
      longitude: -86.747010,
      distanceToCenter: 12.0,
      distanceToAirport: 22.0,
      rating: 4.1,
      reviewCount: 1780,
      nightlyRate: 540.00,
      currency: 'BRL',
      breakfastIncluded: false,
      refundable: true,
      highlights: ['piscina', 'cowork', 'vida_noturna', 'wifi'],
      categoryNames: ['Hotel Boutique', 'Hotel à Beira-Mar'],
    },

    // Los Angeles
    {
      hotelId: 'hotel-lax-001',
      name: 'The Beverly Hills Hotel',
      city: 'Los Angeles',
      address: '9641 Sunset Blvd, Beverly Hills, CA',
      latitude: 34.081997,
      longitude: -118.413742,
      distanceToCenter: 14.0,
      distanceToAirport: 20.0,
      rating: 4.8,
      reviewCount: 2100,
      nightlyRate: 3200.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['spa', 'celebridades', 'piscina', 'restaurante_premiado', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Hotel Boutique'],
    },
    {
      hotelId: 'hotel-lax-002',
      name: 'Santa Monica Proper Hotel',
      city: 'Santa Monica',
      address: '700 Wilshire Blvd, Santa Monica, CA',
      latitude: 34.018372,
      longitude: -118.491210,
      distanceToCenter: 24.0,
      distanceToAirport: 14.0,
      rating: 4.4,
      reviewCount: 1640,
      nightlyRate: 1480.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'praia', 'design', 'wifi'],
      categoryNames: ['Hotel Boutique', 'Hotel à Beira-Mar'],
    },

    // Vancouver
    {
      hotelId: 'hotel-yvr-001',
      name: 'Fairmont Pacific Rim',
      city: 'Vancouver',
      address: '1038 Canada Place, Vancouver, BC',
      latitude: 49.289410,
      longitude: -123.116779,
      distanceToCenter: 0.5,
      distanceToAirport: 14.0,
      rating: 4.7,
      reviewCount: 3120,
      nightlyRate: 1850.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['spa', 'vista_mar', 'restaurante_premiado', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Hotel no Centro'],
    },
    {
      hotelId: 'hotel-yvr-002',
      name: 'The Burrard',
      city: 'Vancouver',
      address: '1100 Burrard St, Vancouver, BC',
      latitude: 49.280905,
      longitude: -123.126672,
      distanceToCenter: 0.6,
      distanceToAirport: 13.0,
      rating: 4.3,
      reviewCount: 2150,
      nightlyRate: 620.00,
      currency: 'BRL',
      breakfastIncluded: false,
      refundable: true,
      highlights: ['bike_gratuita', 'wifi', 'pet_friendly'],
      categoryNames: ['Hotel Boutique', 'Hotel no Centro'],
    },

    // Tóquio
    {
      hotelId: 'hotel-tyo-001',
      name: 'Park Hyatt Tokyo',
      city: 'Tóquio',
      address: '3-7-1-2 Nishi-Shinjuku, Shinjuku-ku',
      latitude: 35.688178,
      longitude: 139.692269,
      distanceToCenter: 1.5,
      distanceToAirport: 24.0,
      rating: 4.9,
      reviewCount: 2560,
      nightlyRate: 3100.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['vista_cidade', 'spa', 'bar_iconico', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Hotel no Centro'],
    },
    {
      hotelId: 'hotel-tyo-002',
      name: 'Shinjuku Granbell Hotel',
      city: 'Tóquio',
      address: '2-14-5 Kabukicho, Shinjuku-ku',
      latitude: 35.696400,
      longitude: 139.704927,
      distanceToCenter: 0.8,
      distanceToAirport: 23.0,
      rating: 4.2,
      reviewCount: 3980,
      nightlyRate: 780.00,
      currency: 'BRL',
      breakfastIncluded: false,
      refundable: true,
      highlights: ['rooftop_bar', 'wifi', 'design_moderno'],
      categoryNames: ['Hotel Boutique', 'Hotel no Centro'],
    },

    // Dubai
    {
      hotelId: 'hotel-dxb-001',
      name: 'Burj Al Arab Jumeirah',
      city: 'Dubai',
      address: 'Jumeirah St, Dubai',
      latitude: 25.141247,
      longitude: 55.185220,
      distanceToCenter: 16.0,
      distanceToAirport: 27.0,
      rating: 4.9,
      reviewCount: 5400,
      nightlyRate: 5200.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: false,
      highlights: ['luxo', 'mayordomo', 'restaurante_premiado', 'spa', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Hotel à Beira-Mar'],
    },
    {
      hotelId: 'hotel-dxb-002',
      name: 'Rove Downtown Dubai',
      city: 'Dubai',
      address: '312 Al Sa\'ada St, Zabeel 2',
      latitude: 25.196754,
      longitude: 55.277664,
      distanceToCenter: 2.5,
      distanceToAirport: 12.0,
      rating: 4.6,
      reviewCount: 6120,
      nightlyRate: 620.00,
      currency: 'BRL',
      breakfastIncluded: false,
      refundable: true,
      highlights: ['vista_burj', 'piscina', 'cozinha_compartilhada', 'wifi'],
      categoryNames: ['Hotel Econômico', 'Hotel no Centro'],
    },

    // Bali (Seminyak e Ubud)
    {
      hotelId: 'hotel-dps-001',
      name: 'Four Seasons Resort Bali at Sayan',
      city: 'Ubud',
      address: 'Sayan, Ubud, Gianyar',
      latitude: -8.506680,
      longitude: 115.248037,
      distanceToCenter: 8.0,
      distanceToAirport: 38.0,
      rating: 4.9,
      reviewCount: 1850,
      nightlyRate: 2400.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['villa_privada', 'spa', 'bem_estar', 'piscina_infinita', 'wifi'],
      categoryNames: ['Resort', 'Hotel de Luxo'],
    },
    {
      hotelId: 'hotel-dps-002',
      name: 'Hotel Indigo Bali Seminyak Beach',
      city: 'Seminyak',
      address: 'Jalan Camplung Tanduk No. 10, Seminyak',
      latitude: -8.689392,
      longitude: 115.159288,
      distanceToCenter: 7.0,
      distanceToAirport: 9.0,
      rating: 4.7,
      reviewCount: 3220,
      nightlyRate: 980.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['praia', 'piscina', 'spa', 'gastronomia', 'wifi'],
      categoryNames: ['Resort', 'Hotel à Beira-Mar'],
    },

    // Cidade do Cabo
    {
      hotelId: 'hotel-cpt-001',
      name: 'One&Only Cape Town',
      city: 'Cidade do Cabo',
      address: 'Dock Rd, V&A Waterfront',
      latitude: -33.907402,
      longitude: 18.420517,
      distanceToCenter: 1.0,
      distanceToAirport: 20.0,
      rating: 4.8,
      reviewCount: 1980,
      nightlyRate: 2100.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['spa', 'vista_montanha', 'gastronomia', 'piscina', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Hotel no Centro'],
    },
    {
      hotelId: 'hotel-cpt-002',
      name: 'The Table Bay Hotel',
      city: 'Cidade do Cabo',
      address: 'Quay 6, Victoria & Alfred Waterfront',
      latitude: -33.906513,
      longitude: 18.420389,
      distanceToCenter: 1.2,
      distanceToAirport: 19.0,
      rating: 4.6,
      reviewCount: 2650,
      nightlyRate: 1350.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['piscina', 'vista_mar', 'wifi', 'servico_quarto'],
      categoryNames: ['Hotel de Luxo', 'Hotel à Beira-Mar'],
    },

    // Sydney
    {
      hotelId: 'hotel-syd-001',
      name: 'Park Hyatt Sydney',
      city: 'Sydney',
      address: '7 Hickson Rd, The Rocks',
      latitude: -33.857150,
      longitude: 151.209319,
      distanceToCenter: 0.8,
      distanceToAirport: 13.0,
      rating: 4.8,
      reviewCount: 2430,
      nightlyRate: 2300.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['vista_opera', 'spa', 'piscina', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Hotel no Centro'],
    },
    {
      hotelId: 'hotel-syd-002',
      name: 'QT Sydney',
      city: 'Sydney',
      address: '49 Market St, Sydney',
      latitude: -33.871351,
      longitude: 151.207828,
      distanceToCenter: 0.5,
      distanceToAirport: 12.0,
      rating: 4.5,
      reviewCount: 3820,
      nightlyRate: 890.00,
      currency: 'BRL',
      breakfastIncluded: false,
      refundable: true,
      highlights: ['design', 'spa', 'bar', 'wifi'],
      categoryNames: ['Hotel Boutique', 'Hotel no Centro'],
    },

    // Queenstown
    {
      hotelId: 'hotel-zqn-001',
      name: 'Matakauri Lodge',
      city: 'Queenstown',
      address: '569 Glenorchy Rd, Queenstown',
      latitude: -45.051995,
      longitude: 168.561420,
      distanceToCenter: 6.0,
      distanceToAirport: 14.0,
      rating: 4.9,
      reviewCount: 760,
      nightlyRate: 3100.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['vista_lago', 'spa', 'gastronomia', 'passeios', 'wifi'],
      categoryNames: ['Hotel de Luxo', 'Resort'],
    },
    {
      hotelId: 'hotel-zqn-002',
      name: 'The Rees Hotel & Luxury Apartments',
      city: 'Queenstown',
      address: '377 Frankton Rd, Queenstown',
      latitude: -45.036669,
      longitude: 168.691611,
      distanceToCenter: 2.5,
      distanceToAirport: 7.0,
      rating: 4.6,
      reviewCount: 1980,
      nightlyRate: 980.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['apartamentos', 'vista_lago', 'wifi', 'transfer_esqui'],
      categoryNames: ['Hotel Boutique', 'Resort'],
    },

    // Marrakesh
    {
      hotelId: 'hotel-rak-001',
      name: 'La Mamounia',
      city: 'Marrakesh',
      address: 'Avenue Bab Jdid, Marrakech 40040',
      latitude: 31.618670,
      longitude: -7.986350,
      distanceToCenter: 1.2,
      distanceToAirport: 5.0,
      rating: 4.9,
      reviewCount: 3120,
      nightlyRate: 2100.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: false,
      highlights: ['spa', 'jardins', 'gastronomia', 'wifi', 'arquitetura'],
      categoryNames: ['Hotel de Luxo', 'Hotel Boutique'],
    },
    {
      hotelId: 'hotel-rak-002',
      name: 'Riad Yasmine',
      city: 'Marrakesh',
      address: '209 Rue Ank Jemel, Marrakech',
      latitude: 31.633700,
      longitude: -7.988300,
      distanceToCenter: 0.5,
      distanceToAirport: 7.0,
      rating: 4.8,
      reviewCount: 1480,
      nightlyRate: 780.00,
      currency: 'BRL',
      breakfastIncluded: true,
      refundable: true,
      highlights: ['riad', 'piscina', 'terraco', 'wifi'],
      categoryNames: ['Hotel Boutique', 'Hotel no Centro'],
    },
  ];

  for (const hotel of hotels) {
    const { categoryNames, ...hotelData } = hotel;
    const media = hotelMedia[hotelData.hotelId];
    const hotelInput = {
      ...hotelData,
      heroImageUrl: media?.heroImageUrl ?? null,
      galleryImageUrls: media?.galleryImageUrls ?? [],
    };

    const createdHotel = await prisma.hotel.upsert({
      where: { hotelId: hotelData.hotelId },
      update: hotelInput,
      create: hotelInput,
    });

    // Link categories
    for (const categoryName of categoryNames) {
      const category = await prisma.category.findFirst({
        where: { name: categoryName }
      });

      if (category) {
        await prisma.hotelCategory.upsert({
          where: {
            hotelId_categoryId: {
              hotelId: createdHotel.id,
              categoryId: category.id
            }
          },
          update: {},
          create: {
            hotelId: createdHotel.id,
            categoryId: category.id
          }
        });
      }
    }
  }

  console.log(`✅ Created ${hotels.length} hotels`);
}
